In [46]:
# Backtest an Automated Trading Strategy in Python

In [47]:
import pandas as pd

In [48]:
df= pd.read_csv('BTC-USDT.csv')
df

                date      open      high       low     close       volume
0      1502942400000   4261.48   4313.62   4261.32   4308.83    47.181009
1      1502946000000   4308.83   4328.69   4291.37   4315.32    23.234916
2      1502949600000   4330.29   4345.45   4309.37   4324.35     7.229691
3      1502953200000   4316.62   4349.99   4287.41   4349.99     4.443249
4      1502956800000   4333.32   4377.85   4333.32   4360.69     0.972807
...              ...       ...       ...       ...       ...          ...
51404  1688364000000  30673.61  30678.41  30606.00  30651.25  1036.522350
51405  1688367600000  30651.25  30759.80  30636.65  30667.19  1758.796390
51406  1688371200000  30667.19  30700.92  30599.07  30640.12  1390.909010
51407  1688374800000  30640.11  30670.00  30602.29  30610.61   833.620010
51408  1688378400000  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 6 columns]

In [49]:
df['date'] = pd.to_datetime(df['date'], unit ="ms")
df

                     date      open      high       low     close       volume
0     2017-08-17 04:00:00   4261.48   4313.62   4261.32   4308.83    47.181009
1     2017-08-17 05:00:00   4308.83   4328.69   4291.37   4315.32    23.234916
2     2017-08-17 06:00:00   4330.29   4345.45   4309.37   4324.35     7.229691
3     2017-08-17 07:00:00   4316.62   4349.99   4287.41   4349.99     4.443249
4     2017-08-17 08:00:00   4333.32   4377.85   4333.32   4360.69     0.972807
...                   ...       ...       ...       ...       ...          ...
51404 2023-07-03 06:00:00  30673.61  30678.41  30606.00  30651.25  1036.522350
51405 2023-07-03 07:00:00  30651.25  30759.80  30636.65  30667.19  1758.796390
51406 2023-07-03 08:00:00  30667.19  30700.92  30599.07  30640.12  1390.909010
51407 2023-07-03 09:00:00  30640.11  30670.00  30602.29  30610.61   833.620010
51408 2023-07-03 10:00:00  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 6 columns]

In [50]:
df.set_index(df['date'],inplace=True)
del df['date']
df

                         open      high       low     close       volume
date
2017-08-17 04:00:00   4261.48   4313.62   4261.32   4308.83    47.181009
2017-08-17 05:00:00   4308.83   4328.69   4291.37   4315.32    23.234916
2017-08-17 06:00:00   4330.29   4345.45   4309.37   4324.35     7.229691
2017-08-17 07:00:00   4316.62   4349.99   4287.41   4349.99     4.443249
2017-08-17 08:00:00   4333.32   4377.85   4333.32   4360.69     0.972807
...                       ...       ...       ...       ...          ...
2023-07-03 06:00:00  30673.61  30678.41  30606.00  30651.25  1036.522350
2023-07-03 07:00:00  30651.25  30759.80  30636.65  30667.19  1758.796390
2023-07-03 08:00:00  30667.19  30700.92  30599.07  30640.12  1390.909010
2023-07-03 09:00:00  30640.11  30670.00  30602.29  30610.61   833.620010
2023-07-03 10:00:00  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 5 columns]

In [51]:
# Creating new columns for Moving Averages
# 50 moving average based on close price. We want to do computation of rolling period 50. Computing mean the average price

df['ma20'] = df['close'].rolling(20).mean()
df['ma50'] = df['close'].rolling(50).mean()
df

,open,high,low,close,volume,ma20,ma50
date,,,,,,,
2017-08-17 04:00:00,4261.48,4313.62,4261.32,4308.83,47.181009,NaN,NaN
2017-08-17 05:00:00,4308.83,4328.69,4291.37,4315.32,23.234916,NaN,NaN
2017-08-17 06:00:00,4330.29,4345.45,4309.37,4324.35,7.229691,NaN,NaN
2017-08-17 07:00:00,4316.62,4349.99,4287.41,4349.99,4.443249,NaN,NaN
2017-08-17 08:00:00,4333.32,4377.85,4333.32,4360.69,0.972807,NaN,NaN
...,...,...,...,...,...,...,...
2023-07-03 06:00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,30599.5055,30558.3664
2023-07-03 07:00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,30605.6280,30563.1230
2023-07-03 08:00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,30611.3345,30566.9202
2023-07-03 09:00:00,30640.11,30670.00,30602.29,30610.61,833.620010,30615.9670,30569.9348
2023-07-03 10:00:00,30610.60,30623.08,30605.66,30615.85,91.875210,30617.2480,30573.4178

In [52]:
df['buy_signal'] = False
df['sell_signal'] = False
df.loc[df['ma20']> df['ma50'], 'buy_signal'] =True # Moving Average cross over
df.loc[df['ma20']< df['ma50'], 'sell_signal'] = True # Moving Average cross over
df

,open,high,low,close,volume,ma20,ma50,buy_signal,sell_signal
date,,,,,,,,,
2017-08-17 04:00:00,4261.48,4313.62,4261.32,4308.83,47.181009,NaN,NaN,False,False
2017-08-17 05:00:00,4308.83,4328.69,4291.37,4315.32,23.234916,NaN,NaN,False,False
2017-08-17 06:00:00,4330.29,4345.45,4309.37,4324.35,7.229691,NaN,NaN,False,False
2017-08-17 07:00:00,4316.62,4349.99,4287.41,4349.99,4.443249,NaN,NaN,False,False
2017-08-17 08:00:00,4333.32,4377.85,4333.32,4360.69,0.972807,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...
2023-07-03 06:00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,30599.5055,30558.3664,True,False
2023-07-03 07:00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,30605.6280,30563.1230,True,False
2023-07-03 08:00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,30611.3345,30566.9202,True,False
2023-07-03 09:00:00,30640.11,30670.00,30602.29,30610.61,833.620010,30615.9670,30569.9348,True,False
2023-07-03 10:00:00,30610.60,30623.08,30605.66,30615.85,91.875210,30617.2480,30573.4178,True,False

In [53]:
df['sell_signal'].value_counts()

sell_signal
False    27090
True     24319
Name: count, dtype: int64

In [54]:
# Backtesting

balance = 1000
position = None

for index, row in df.iterrows():    # Loop going to return 2 values 
    # buy condition
    if position is None and row['buy_signal'] is True:
        buy_price = row['close']
        usd_size = balance          # How much we are going to buy
        position = {
            'buy_price': buy_price,
            'usd_size': usd_size
        }
        print(f'{index} - Bought Bitcoin for {usd_size}$ at price of {buy_price}$')
        
    if position and row['sell_signal'] is True:
        sell_price = row['close']
        trade_results = (sell_price - position['buy_price']) / position['buy_price']
        balance += trade_results *position['usd_size']
        print(f'{index} - Sold Bitcoin for {balance}$ at price of {sell_price}$({round(trade_results*100,2)}%)')
        position = None

2017-08-20 13:00:00 - Bought Bitcoin for 1000$ at price of 4063.35$
2017-08-21 12:00:00 - Sold Bitcoin for 984.4094158760629$ at price of 4000.0$(-1.56%)
2017-08-23 03:00:00 - Bought Bitcoin for 984.4094158760629$ at price of 4100.41$
2017-08-26 14:00:00 - Sold Bitcoin for 1026.084182668146$ at price of 4274.0$(4.23%)
2017-08-27 11:00:00 - Bought Bitcoin for 1026.084182668146$ at price of 4323.37$
2017-08-28 05:00:00 - Sold Bitcoin for 989.4492533337021$ at price of 4169.01$(-3.57%)
2017-08-29 02:00:00 - Bought Bitcoin for 989.4492533337021$ at price of 4314.78$
2017-09-02 14:00:00 - Sold Bitcoin for 1028.2403934831254$ at price of 4483.94$(3.92%)
2017-09-05 23:00:00 - Bought Bitcoin for 1028.2403934831254$ at price of 4366.47$
2017-09-08 16:00:00 - Sold Bitcoin for 1004.8190051452159$ at price of 4267.01$(-2.28%)
2017-09-11 08:00:00 - Bought Bitcoin for 1004.8190051452159$ at price of 4166.62$
2017-09-13 02:00:00 - Sold Bitcoin for 970.1837119053822$ at price of 4023.0$(-3.45%)
2017-09-16 03:00:00 - Bought Bitcoin for 970.1837119053822$ at price of 3770.0$
2017-09-17 10:00:00 - Sold Bitcoin for 920.6297130819073$ at price of 3577.44$(-5.11%)
2017-09-18 04:00:00 - Bought Bitcoin for 920.6297130819073$ at price of 3769.06$
2017-09-20 00:00:00 - Sold Bitcoin for 946.5065926762617$ at price of 3875.0$(2.81%)
2017-09-20 21:00:00 - Bought Bitcoin for 946.5065926762617$ at price of 3960.0$
2017-09-21 09:00:00 - Sold Bitcoin for 922.6049110430228$ at price of 3860.0$(-2.53%)
2017-09-23 13:00:00 - Bought Bitcoin for 922.6049110430228$ at price of 3780.0$
2017-09-24 19:00:00 - Sold Bitcoin for 899.99376846127$ at price of 3687.36$(-2.45%)
2017-09-25 12:00:00 - Bought Bitcoin for 899.99376846127$ at price of 3791.99$
2017-09-29 07:00:00 - Sold Bitcoin for 970.7474208485361$ at price of 4090.1$(7.86%)
2017-09-30 03:00:00 - Bought Bitcoin for 970.7474208485361$ at price of 4214.0$
2017-10-03 09:00:00 - Sold Bitcoin for 981.5859747524098$ at price of 4261.05$(1.12%)
2017-10-05 21:00:00 - Bought Bitcoin for 981.5859747524098$ at price of 4323.01$
2017-10-07 20:00:00 - Sold Bitcoin for 985.2189470555131$ at price of 4339.01$(0.37%)
2017-10-08 00:00:00 - Bought Bitcoin for 985.2189470555131$ at price of 4450.0$
2017-10-11 15:00:00 - Sold Bitcoin for 1068.2452296027689$ at price of 4825.01$(8.43%)
2017-10-12 02:00:00 - Bought Bitcoin for 1068.2452296027689$ at price of 4877.53$
2017-10-15 16:00:00 - Sold Bitcoin for 1204.528610037665$ at price of 5499.79$(12.76%)
2017-10-16 16:00:00 - Bought Bitcoin for 1204.528610037665$ at price of 5664.71$
2017-10-17 15:00:00 - Sold Bitcoin for 1191.408888950562$ at price of 5603.01$(-1.09%)
2017-10-19 10:00:00 - Bought Bitcoin for 1191.408888950562$ at price of 5689.99$
2017-10-22 11:00:00 - Sold Bitcoin for 1218.6270811573468$ at price of 5819.98$(2.28%)
2017-10-26 05:00:00 - Bought Bitcoin for 1218.6270811573468$ at price of 5699.99$
2017-10-27 23:00:00 - Sold Bitcoin for 1233.3447014105177$ at price of 5768.83$(1.21%)
2017-10-29 15:00:00 - Bought Bitcoin for 1233.3447014105177$ at price of 5949.01$
2017-11-06 11:00:00 - Sold Bitcoin for 1514.2831104704103$ at price of 7304.11$(22.78%)
2017-11-08 09:00:00 - Bought Bitcoin for 1514.2831104704103$ at price of 7325.03$
2017-11-09 13:00:00 - Sold Bitcoin for 1471.8936933892574$ at price of 7119.98$(-2.8%)
2017-11-13 14:00:00 - Bought Bitcoin for 1471.8936933892574$ at price of 6405.03$
2017-11-18 10:00:00 - Sold Bitcoin for 1771.9242016131088$ at price of 7710.63$(20.38%)
2017-11-19 03:00:00 - Bought Bitcoin for 1771.9242016131088$ at price of 7779.99$
2017-11-22 14:00:00 - Sold Bitcoin for 1869.1592365417764$ at price of 8206.92$(5.49%)
2017-11-22 15:00:00 - Bought Bitcoin for 1869.1592365417764$ at price of 8205.02$
2017-11-23 06:00:00 - Sold Bitcoin for 1878.2578395808277$ at price of 8244.96$(0.49%)
2017-11-24 21:00:00 - Bought Bitcoin for 1878.2578395808277$ at price of 8221.16$
2017-11-30 10:00:00 - Sold Bitcoin for 2148.074231180865$ at price of 9402.15$(14.37%)
2017-12-01 16:00:00 - Bought Bitcoin for 2148.074231180865$ at price of 10536.11$
2017-12-05 04:00:00 - Sold Bitcoin for 2344.591612969327$ at price of 11500.01$(9.15%)
2017-12-05 07:00:00 - Bought Bitcoin for 2344.591612969327$ at price of 11780.0$
2017-12-09 09:00:00 - Sold Bitcoin for 2965.562075515997$ at price of 14899.96$(26.49%)
2017-12-11 01:00:00 - Bought Bitcoin for 2965.562075515997$ at price of 16022.52$
2017-12-13 02:00:00 - Sold Bitcoin for 2831.8273772498014$ at price of 15299.97$(-4.51%)
2017-12-14 19:00:00 - Bought Bitcoin for 2831.8273772498014$ at price of 16350.0$
2017-12-18 09:00:00 - Sold Bitcoin for 3235.467564780879$ at price of 18680.48$(14.25%)
2017-12-23 15:00:00 - Bought Bitcoin for 3235.467564780879$ at price of 14218.39$
2017-12-24 11:00:00 - Sold Bitcoin for 2809.37058649767$ at price of 12345.89$(-13.17%)
2017-12-25 15:00:00 - Bought Bitcoin for 2809.37058649767$ at price of 13473.0$
2017-12-28 02:00:00 - Sold Bitcoin for 2882.170672066135$ at price of 13822.13$(2.59%)
2017-12-29 16:00:00 - Bought Bitcoin for 2882.170672066135$ at price of 14596.0$
2017-12-30 07:00:00 - Sold Bitcoin for 2689.446735649545$ at price of 13620.0$(-6.69%)
2017-12-31 21:00:00 - Bought Bitcoin for 2689.446735649545$ at price of 13940.99$
2018-01-02 05:00:00 - Sold Bitcoin for 2540.121662519002$ at price of 13166.95$(-5.55%)
2018-01-02 16:00:00 - Bought Bitcoin for 2540.121662519002$ at price of 13590.02$
2018-01-04 17:00:00 - Sold Bitcoin for 2738.0359131817304$ at price of 14648.89$(7.79%)
2018-01-05 08:00:00 - Bought Bitcoin for 2738.0359131817304$ at price of 15424.81$
2018-01-07 17:00:00 - Sold Bitcoin for 2804.637127370157$ at price of 15800.01$(2.43%)
2018-01-12 21:00:00 - Bought Bitcoin for 2804.637127370157$ at price of 13700.81$
2018-01-14 11:00:00 - Sold Bitcoin for 2718.525528566909$ at price of 13280.15$(-3.07%)
2018-01-15 18:00:00 - Bought Bitcoin for 2718.525528566909$ at price of 13827.95$
2018-01-16 08:00:00 - Sold Bitcoin for 2327.438227215453$ at price of 11838.66$(-14.39%)
2018-01-18 11:00:00 - Bought Bitcoin for 2327.438227215453$ at price of 11413.78$
2018-01-21 16:00:00 - Sold Bitcoin for 2279.767034257605$ at price of 11180.0$(-2.05%)
2018-01-24 07:00:00 - Bought Bitcoin for 2279.767034257605$ at price of 10956.0$
2018-01-26 07:00:00 - Sold Bitcoin for 2291.0035639992907$ at price of 11010.0$(0.49%)
2018-01-27 15:00:00 - Bought Bitcoin for 2291.0035639992907$ at price of 11464.97$
2018-01-29 13:00:00 - Sold Bitcoin for 2269.9218798778384$ at price of 11359.47$(-0.92%)
2018-02-03 17:00:00 - Bought Bitcoin for 2269.9218798778384$ at price of 9211.31$
2018-02-04 18:00:00 - Sold Bitcoin for 2057.434672372906$ at price of 8349.04$(-9.36%)
2018-02-07 04:00:00 - Bought Bitcoin for 2057.434672372906$ at price of 7460.0$
2018-02-11 03:00:00 - Sold Bitcoin for 2197.82838818677$ at price of 7969.05$(6.82%)
2018-02-12 07:00:00 - Bought Bitcoin for 2197.82838818677$ at price of 8473.76$
2018-02-13 22:00:00 - Sold Bitcoin for 2225.383722295945$ at price of 8580.0$(1.25%)
2018-02-14 11:00:00 - Bought Bitcoin for 2225.383722295945$ at price of 8927.0$
2018-02-18 22:00:00 - Sold Bitcoin for 2634.9620191181966$ at price of 10570.0$(18.4%)
2018-02-19 15:00:00 - Bought Bitcoin for 2634.9620191181966$ at price of 11171.71$
2018-02-21 11:00:00 - Sold Bitcoin for 2582.197728486151$ at price of 10948.0$(-2.0%)
2018-02-24 02:00:00 - Bought Bitcoin for 2582.197728486151$ at price of 10420.0$
2018-02-24 20:00:00 - Sold Bitcoin for 2325.960449095107$ at price of 9386.0$(-9.92%)
2018-02-26 13:00:00 - Bought Bitcoin for 2325.960449095107$ at price of 10114.94$
2018-03-01 00:00:00 - Sold Bitcoin for 2393.8103711025533$ at price of 10410.0$(2.92%)
2018-03-01 19:00:00 - Bought Bitcoin for 2393.8103711025533$ at price of 10880.0$
2018-03-04 16:00:00 - Sold Bitcoin for 2456.416873041637$ at price of 11164.55$(2.62%)
2018-03-05 05:00:00 - Bought Bitcoin for 2456.416873041637$ at price of 11530.0$
2018-03-06 11:00:00 - Sold Bitcoin for 2330.0807754081857$ at price of 10937.0$(-5.14%)
2018-03-10 12:00:00 - Bought Bitcoin for 2330.0807754081857$ at price of 9259.0$
2018-03-11 05:00:00 - Sold Bitcoin for 2222.8829670162836$ at price of 8833.03$(-4.6%)
2018-03-11 23:00:00 - Bought Bitcoin for 2222.8829670162836$ at price of 9533.57$
2018-03-13 05:00:00 - Sold Bitcoin for 2187.076009366139$ at price of 9380.0$(-1.61%)
2018-03-16 14:00:00 - Bought Bitcoin for 2187.076009366139$ at price of 8418.5$
2018-03-17 15:00:00 - Sold Bitcoin for 2049.024061796254$ at price of 7887.11$(-6.31%)
2018-03-19 07:00:00 - Bought Bitcoin for 2049.024061796254$ at price of 8289.01$
2018-03-22 13:00:00 - Sold Bitcoin for 2122.968304547211$ at price of 8588.14$(3.61%)
2018-03-24 05:00:00 - Bought Bitcoin for 2122.968304547211$ at price of 8845.0$
2018-03-25 08:00:00 - Sold Bitcoin for 2045.922196490721$ at price of 8524.0$(-3.63%)
2018-03-29 00:00:00 - Bought Bitcoin for 2045.922196490721$ at price of 7958.99$
2018-03-29 05:00:00 - Sold Bitcoin for 1944.643907889356$ at price of 7565.0$(-4.95%)
2018-03-31 18:00:00 - Bought Bitcoin for 1944.643907889356$ at price of 7021.0$
2018-04-01 10:00:00 - Sold Bitcoin for 1857.681958343704$ at price of 6707.03$(-4.47%)
2018-04-02 11:00:00 - Bought Bitcoin for 1857.681958343704$ at price of 7046.01$
2018-04-04 16:00:00 - Sold Bitcoin for 1816.5472538597783$ at price of 6889.99$(-2.21%)
2018-04-07 10:00:00 - Bought Bitcoin for 1816.5472538597783$ at price of 6860.0$
2018-04-09 15:00:00 - Sold Bitcoin for 1784.5008181947476$ at price of 6738.98$(-1.76%)
2018-04-11 06:00:00 - Bought Bitcoin for 1784.5008181947476$ at price of 6833.07$
2018-04-16 16:00:00 - Sold Bitcoin for 2078.0407526094245$ at price of 7957.07$(16.45%)
2018-04-18 19:00:00 - Bought Bitcoin for 2078.0407526094245$ at price of 8116.65$
2018-04-25 19:00:00 - Sold Bitcoin for 2296.5119834034344$ at price of 8969.98$(10.51%)
2018-04-27 05:00:00 - Bought Bitcoin for 2296.5119834034344$ at price of 9180.82$
2018-04-28 14:00:00 - Sold Bitcoin for 2329.0805187019296$ at price of 9311.02$(1.42%)
2018-04-28 15:00:00 - Bought Bitcoin for 2329.0805187019296$ at price of 9360.0$
2018-04-30 04:00:00 - Sold Bitcoin for 2307.929680658162$ at price of 9275.0$(-0.91%)
2018-05-02 15:00:00 - Bought Bitcoin for 2307.929680658162$ at price of 9155.0$
2018-05-06 12:00:00 - Sold Bitcoin for 2403.725778817649$ at price of 9535.0$(4.15%)
2018-05-10 01:00:00 - Bought Bitcoin for 2403.725778817649$ at price of 9318.0$
2018-05-11 01:00:00 - Sold Bitcoin for 2301.052791349607$ at price of 8919.99$(-4.27%)
2018-05-13 14:00:00 - Bought Bitcoin for 2301.052791349607$ at price of 8654.41$
2018-05-16 01:00:00 - Sold Bitcoin for 2210.812403225627$ at price of 8315.01$(-3.92%)
2018-05-19 05:00:00 - Bought Bitcoin for 2210.812403225627$ at price of 8224.03$
2018-05-22 03:00:00 - Sold Bitcoin for 2237.9393810709776$ at price of 8324.94$(1.23%)
2018-05-26 19:00:00 - Bought Bitcoin for 2237.9393810709776$ at price of 7533.35$
2018-05-27 03:00:00 - Sold Bitcoin for 2168.008881319325$ at price of 7297.95$(-3.12%)
2018-05-29 19:00:00 - Bought Bitcoin for 2168.008881319325$ at price of 7473.01$
2018-05-31 06:00:00 - Sold Bitcoin for 2194.6962719413855$ at price of 7565.0$(1.23%)
2018-05-31 15:00:00 - Bought Bitcoin for 2194.6962719413855$ at price of 7558.63$
2018-06-01 20:00:00 - Sold Bitcoin for 2161.676947004833$ at price of 7444.91$(-1.5%)
2018-06-02 10:00:00 - Bought Bitcoin for 2161.676947004833$ at price of 7660.0$
2018-06-04 11:00:00 - Sold Bitcoin for 2117.935442202516$ at price of 7505.0$(-2.02%)
2018-06-06 02:00:00 - Bought Bitcoin for 2117.935442202516$ at price of 7616.19$
2018-06-08 11:00:00 - Sold Bitcoin for 2102.0290759887025$ at price of 7558.99$(-0.75%)
2018-06-12 14:00:00 - Bought Bitcoin for 2102.0290759887025$ at price of 6742.4$
2018-06-12 21:00:00 - Sold Bitcoin for 2037.3663667678293$ at price of 6534.99$(-3.08%)
2018-06-14 19:00:00 - Bought Bitcoin for 2037.3663667678293$ at price of 6642.0$
2018-06-16 01:00:00 - Sold Bitcoin for 1975.68710916023$ at price of 6440.92$(-3.03%)
2018-06-17 07:00:00 - Bought Bitcoin for 1975.68710916023$ at price of 6527.79$
2018-06-18 04:00:00 - Sold Bitcoin for 1938.6750765153065$ at price of 6405.5$(-1.87%)
2018-06-18 21:00:00 - Bought Bitcoin for 1938.6750765153065$ at price of 6716.24$
2018-06-20 12:00:00 - Sold Bitcoin for 1908.5856976402283$ at price of 6612.0$(-1.55%)
2018-06-21 01:00:00 - Bought Bitcoin for 1908.5856976402283$ at price of 6759.98$
2018-06-22 05:00:00 - Sold Bitcoin for 1877.5343846146764$ at price of 6650.0$(-1.63%)
2018-06-25 05:00:00 - Bought Bitcoin for 1877.5343846146764$ at price of 6152.03$
2018-06-27 03:00:00 - Sold Bitcoin for 1840.8414622683579$ at price of 6031.8$(-1.95%)
2018-06-28 17:00:00 - Bought Bitcoin for 1840.8414622683579$ at price of 6106.58$
2018-06-28 19:00:00 - Sold Bitcoin for 1835.2706271654495$ at price of 6088.1$(-0.3%)
2018-06-30 04:00:00 - Bought Bitcoin for 1835.2706271654495$ at price of 6383.67$
2018-07-01 23:00:00 - Sold Bitcoin for 1827.548522318917$ at price of 6356.81$(-0.42%)
2018-07-02 14:00:00 - Bought Bitcoin for 1827.548522318917$ at price of 6612.98$
2018-07-04 19:00:00 - Sold Bitcoin for 1846.9184396526052$ at price of 6683.07$(1.06%)
2018-07-05 01:00:00 - Bought Bitcoin for 1846.9184396526052$ at price of 6635.98$
2018-07-05 19:00:00 - Sold Bitcoin for 1811.9448907379392$ at price of 6510.32$(-1.89%)
2018-07-07 03:00:00 - Bought Bitcoin for 1811.9448907379392$ at price of 6599.99$
2018-07-09 20:00:00 - Sold Bitcoin for 1838.6491553689584$ at price of 6697.26$(1.47%)
2018-07-13 21:00:00 - Bought Bitcoin for 1838.6491553689584$ at price of 6220.68$
2018-07-14 13:00:00 - Sold Bitcoin for 1843.7211442039622$ at price of 6237.84$(0.28%)
2018-07-14 15:00:00 - Bought Bitcoin for 1843.7211442039622$ at price of 6242.01$
2018-07-19 18:00:00 - Sold Bitcoin for 2193.7351811360168$ at price of 7427.0$(18.98%)
2018-07-19 22:00:00 - Bought Bitcoin for 2193.7351811360168$ at price of 7485.95$
2018-07-21 01:00:00 - Sold Bitcoin for 2130.2260355424987$ at price of 7269.23$(-2.9%)
2018-07-22 03:00:00 - Bought Bitcoin for 2130.2260355424987$ at price of 7422.93$
2018-07-26 04:00:00 - Sold Bitcoin for 2360.8137710537317$ at price of 8226.43$(10.82%)
2018-07-28 04:00:00 - Bought Bitcoin for 2360.8137710537317$ at price of 8217.84$
2018-07-30 11:00:00 - Sold Bitcoin for 2342.761151706918$ at price of 8155.0$(-0.76%)
2018-08-06 11:00:00 - Bought Bitcoin for 2342.761151706918$ at price of 6980.0$
2018-08-06 20:00:00 - Sold Bitcoin for 2323.629721098423$ at price of 6923.0$(-0.82%)
2018-08-07 17:00:00 - Bought Bitcoin for 2323.629721098423$ at price of 7116.41$
2018-08-08 00:00:00 - Sold Bitcoin for 2155.6954342662507$ at price of 6602.09$(-7.23%)
2018-08-10 01:00:00 - Bought Bitcoin for 2155.6954342662507$ at price of 6522.49$
2018-08-10 21:00:00 - Sold Bitcoin for 2007.0621131422295$ at price of 6072.77$(-6.89%)
2018-08-12 06:00:00 - Bought Bitcoin for 2007.0621131422295$ at price of 6339.81$
2018-08-14 02:00:00 - Sold Bitcoin for 1876.9284100457257$ at price of 5928.75$(-6.48%)
2018-08-15 10:00:00 - Bought Bitcoin for 1876.9284100457257$ at price of 6296.3$
2018-08-18 20:00:00 - Sold Bitcoin for 1895.0558843742806$ at price of 6357.11$(0.97%)
2018-08-20 02:00:00 - Bought Bitcoin for 1895.0558843742806$ at price of 6491.68$
2018-08-21 01:00:00 - Sold Bitcoin for 1840.440437308562$ at price of 6304.59$(-2.88%)
2018-08-22 00:00:00 - Bought Bitcoin for 1840.440437308562$ at price of 6461.32$
2018-08-23 04:00:00 - Sold Bitcoin for 1820.703894635995$ at price of 6392.03$(-1.07%)
2018-08-24 08:00:00 - Bought Bitcoin for 1820.703894635995$ at price of 6522.0$
2018-08-26 15:00:00 - Sold Bitcoin for 1863.6950629546004$ at price of 6676.0$(2.36%)
2018-08-27 06:00:00 - Bought Bitcoin for 1863.6950629546004$ at price of 6719.39$
2018-08-30 06:00:00 - Sold Bitcoin for 1936.9793208312624$ at price of 6983.61$(3.93%)
2018-08-31 16:00:00 - Bought Bitcoin for 1936.9793208312624$ at price of 6988.86$
2018-09-05 12:00:00 - Sold Bitcoin for 1936.3945292676951$ at price of 6986.75$(-0.03%)
2018-09-10 01:00:00 - Bought Bitcoin for 1936.3945292676951$ at price of 6334.97$
2018-09-11 04:00:00 - Sold Bitcoin for 1933.640464969253$ at price of 6325.96$(-0.14%)
2018-09-13 01:00:00 - Bought Bitcoin for 1933.640464969253$ at price of 6400.05$
2018-09-16 12:00:00 - Sold Bitcoin for 1964.6630668150262$ at price of 6502.73$(1.6%)
2018-09-19 06:00:00 - Bought Bitcoin for 1964.6630668150262$ at price of 6351.51$
2018-09-23 03:00:00 - Sold Bitcoin for 2076.046898963511$ at price of 6711.6$(5.67%)
2018-09-23 04:00:00 - Bought Bitcoin for 2076.046898963511$ at price of 6728.44$
2018-09-23 05:00:00 - Sold Bitcoin for 2076.2505406625255$ at price of 6729.1$(0.01%)
2018-09-23 11:00:00 - Bought Bitcoin for 2076.2505406625255$ at price of 6747.24$
2018-09-23 20:00:00 - Sold Bitcoin for 2057.030443442065$ at price of 6684.78$(-0.93%)
2018-09-23 21:00:00 - Bought Bitcoin for 2057.030443442065$ at price of 6689.02$
2018-09-24 05:00:00 - Sold Bitcoin for 2056.642963907135$ at price of 6687.76$(-0.02%)
2018-09-26 18:00:00 - Bought Bitcoin for 2056.642963907135$ at price of 6520.01$
2018-09-29 07:00:00 - Sold Bitcoin for 2064.7812011903297$ at price of 6545.81$(0.4%)
2018-09-30 13:00:00 - Bought Bitcoin for 2064.7812011903297$ at price of 6642.03$
2018-10-01 21:00:00 - Sold Bitcoin for 2051.718612482658$ at price of 6600.01$(-0.63%)
2018-10-04 08:00:00 - Bought Bitcoin for 2051.718612482658$ at price of 6600.95$
2018-10-07 04:00:00 - Sold Bitcoin for 2047.8613149753432$ at price of 6588.54$(-0.19%)
2018-10-08 08:00:00 - Bought Bitcoin for 2047.8613149753432$ at price of 6597.54$
2018-10-10 03:00:00 - Sold Bitcoin for 2053.609880585153$ at price of 6616.06$(0.28%)
2018-10-13 01:00:00 - Bought Bitcoin for 2053.609880585153$ at price of 6318.3$
2018-10-17 01:00:00 - Sold Bitcoin for 2194.8465482820766$ at price of 6752.84$(6.88%)
2018-10-20 23:00:00 - Bought Bitcoin for 2194.8465482820766$ at price of 6588.4$
2018-10-22 12:00:00 - Sold Bitcoin for 2193.3041192373094$ at price of 6583.77$(-0.07%)
2018-10-24 09:00:00 - Bought Bitcoin for 2193.3041192373094$ at price of 6605.11$
2018-10-25 06:00:00 - Sold Bitcoin for 2176.1796968690114$ at price of 6553.54$(-0.78%)
2018-10-27 00:00:00 - Bought Bitcoin for 2176.1796968690114$ at price of 6544.11$
2018-10-27 05:00:00 - Sold Bitcoin for 2176.2295779001265$ at price of 6544.26$(0.0%)
2018-11-01 01:00:00 - Bought Bitcoin for 2176.2295779001265$ at price of 6361.9$
2018-11-03 14:00:00 - Sold Bitcoin for 2179.1303507542416$ at price of 6370.38$(0.13%)
2018-11-04 18:00:00 - Bought Bitcoin for 2179.1303507542416$ at price of 6493.75$
2018-11-08 15:00:00 - Sold Bitcoin for 2194.3184069121066$ at price of 6539.01$(0.7%)
2018-11-11 02:00:00 - Bought Bitcoin for 2194.3184069121066$ at price of 6438.24$
2018-11-11 13:00:00 - Sold Bitcoin for 2184.03910027668$ at price of 6408.08$(-0.47%)
2018-11-12 12:00:00 - Bought Bitcoin for 2184.03910027668$ at price of 6447.17$
2018-11-14 13:00:00 - Sold Bitcoin for 2155.6612297644742$ at price of 6363.4$(-1.3%)
2018-11-18 06:00:00 - Bought Bitcoin for 2155.6612297644742$ at price of 5668.88$
2018-11-19 06:00:00 - Sold Bitcoin for 2080.0384702840724$ at price of 5470.01$(-3.51%)
2018-11-22 18:00:00 - Bought Bitcoin for 2080.0384702840724$ at price of 4532.45$
2018-11-22 19:00:00 - Sold Bitcoin for 2063.310783880063$ at price of 4496.0$(-0.8%)
2018-11-24 16:00:00 - Bought Bitcoin for 2063.310783880063$ at price of 4338.13$
2018-11-24 20:00:00 - Sold Bitcoin for 2033.812697189198$ at price of 4276.11$(-1.43%)
2018-11-26 11:00:00 - Bought Bitcoin for 2033.812697189198$ at price of 4057.89$
2018-11-27 01:00:00 - Sold Bitcoin for 1907.2497833856655$ at price of 3805.37$(-6.22%)
2018-11-28 07:00:00 - Bought Bitcoin for 1907.2497833856655$ at price of 4106.8$

In [55]:
print(f"Our final balance is {round(balance,2)}$")

Our final balance is 15486.12$

In [56]:
# Trading strategy written with Functions

class BacktestCrossMA:
    def __init__(self) -> None:
        self.df = pd.DataFrame()
        
    def load_data(self,path):
        self.df =pd.read_csv(path)
        self.df['date'] = pd.to_datetime(self.df['date'], unit ='ms')
        self.df = self.df.set_index(self.df['date'])
        del self.df['date']
    
    def populate_indicators(self):
        self.df['ma20'] = self.df['close'].rolling(20).mean()
        self.df['ma50'] = self.df['close'].rolling(50).mean()
        
    def populate_signals(self):
        self.df['buy_signal'] = False
        self.df['sell_signal'] = False
        self.df.loc[(self.df['ma20'] > self.df['ma50']), 'buy_signal'] = True
        self.df.loc[(self.df['ma20'] < self.df['ma50']), 'sell_signal'] = True
        
    def run_backtest(self):
        balance = 1000
        position = None
        asset = 'BNB'
        
        for index, row in self.df.iterrows():
            
            if position is None and row['buy_signal']:
                open_price = row['close']
                position = {
                    'open_price': open_price,
                    'usd_size': balance,
                }
                print(f"{index} - Buy for {balance}$ of {asset} at {open_price}$")
        
            elif position and row['sell_signal']:
                close_price = row['close']
                trade_results = (close_price - position['open_price']) / position['open_price']
                balance = balance + trade_results * position['usd_size']
                position = None
                print(f"{index} - Sell for {balance}$ of {asset} at {close_price}$")
        
        print(f"Final balance: {balance}$")
        
bt = BacktestCrossMA()
bt.load_data('BNB-USDT.csv')
bt. populate_indicators()
bt.populate_signals()
bt.run_backtest()

#bt = BacktestCrossMA()
#bt.load_data('BTC-USDT.csv')
#bt. populate_indicators()
#bt.populate_signals()
#bt.run_backtest()

2017-11-08 04:00:00 - Buy for 1000$ of BNB at 1.9$
2017-11-10 12:00:00 - Sell for 894.7368421052631$ of BNB at 1.7$
2017-11-13 12:00:00 - Buy for 894.7368421052631$ of BNB at 1.705$
2017-11-14 20:00:00 - Sell for 844.8309924371044$ of BNB at 1.6099$
2017-11-16 13:00:00 - Buy for 844.8309924371044$ of BNB at 1.5455$
2017-11-17 08:00:00 - Sell for 828.7051339596572$ of BNB at 1.516$
2017-11-18 16:00:00 - Buy for 828.7051339596572$ of BNB at 1.5819$
2017-11-20 06:00:00 - Sell for 836.2488180920417$ of BNB at 1.5963$
2017-11-21 10:00:00 - Buy for 836.2488180920417$ of BNB at 1.6154$
2017-11-21 13:00:00 - Sell for 824.6529449180528$ of BNB at 1.593$
2017-11-21 14:00:00 - Buy for 824.6529449180528$ of BNB at 1.6166$
2017-11-21 16:00:00 - Sell for 812.6652273592415$ of BNB at 1.5931$
2017-11-24 11:00:00 - Buy for 812.6652273592415$ of BNB at 1.6869$
2017-11-27 09:00:00 - Sell for 848.7965285934243$ of BNB at 1.7619$
2017-11-28 05:00:00 - Buy for 848.7965285934243$ of BNB at 1.8617$
2017-11-29 23:00:00 - Sell for 800.8331645669817$ of BNB at 1.7565$
2017-11-30 01:00:00 - Buy for 800.8331645669817$ of BNB at 1.885$
2017-11-30 06:00:00 - Sell for 820.2910738174686$ of BNB at 1.9308$
2017-12-01 09:00:00 - Buy for 820.2910738174686$ of BNB at 2.02$
2017-12-06 19:00:00 - Sell for 991.3745537181119$ of BNB at 2.4413$
2017-12-07 14:00:00 - Buy for 991.3745537181119$ of BNB at 2.7499$
2017-12-08 09:00:00 - Sell for 829.1797787380114$ of BNB at 2.3$
2017-12-09 00:00:00 - Buy for 829.1797787380114$ of BNB at 2.79$
2017-12-09 18:00:00 - Sell for 702.5738340274762$ of BNB at 2.364$
2017-12-11 04:00:00 - Buy for 702.5738340274762$ of BNB at 2.5166$
2017-12-12 21:00:00 - Sell for 718.5426901454018$ of BNB at 2.5738$
2017-12-13 23:00:00 - Buy for 718.5426901454018$ of BNB at 2.719$
2017-12-19 04:00:00 - Sell for 1582.617362439782$ of BNB at 5.9887$
2017-12-19 07:00:00 - Buy for 1582.617362439782$ of BNB at 6.323$
2017-12-20 02:00:00 - Sell for 1321.5593347591412$ of BNB at 5.28$
2017-12-23 15:00:00 - Buy for 1321.5593347591412$ of BNB at 4.6997$
2017-12-24 16:00:00 - Sell for 1324.5400630925342$ of BNB at 4.7103$
2017-12-24 22:00:00 - Buy for 1324.5400630925342$ of BNB at 4.98$
2017-12-28 08:00:00 - Sell for 2228.844523838441$ of BNB at 8.38$
2017-12-29 12:00:00 - Buy for 2228.844523838441$ of BNB at 8.5485$
2017-12-30 03:00:00 - Sell for 2131.9835844214695$ of BNB at 8.177$
2017-12-31 18:00:00 - Buy for 2131.9835844214695$ of BNB at 8.41$
2018-01-02 02:00:00 - Sell for 2176.347095393379$ of BNB at 8.585$
2018-01-02 12:00:00 - Buy for 2176.347095393379$ of BNB at 8.45$
2018-01-08 06:00:00 - Sell for 4664.568592894669$ of BNB at 18.1109$
2018-01-09 11:00:00 - Buy for 4664.568592894669$ of BNB at 18.3399$
2018-01-09 23:00:00 - Sell for 4425.260167600387$ of BNB at 17.399$
2018-01-11 12:00:00 - Buy for 4425.260167600387$ of BNB at 18.4999$
2018-01-13 20:00:00 - Sell for 5131.200621690531$ of BNB at 21.4511$
2018-01-15 13:00:00 - Buy for 5131.200621690531$ of BNB at 19.4553$
2018-01-16 00:00:00 - Sell for 4768.474772435521$ of BNB at 18.08$
2018-01-18 09:00:00 - Buy for 4768.474772435521$ of BNB at 14.2697$
2018-01-21 12:00:00 - Sell for 4845.366791548566$ of BNB at 14.4998$
2018-01-24 05:00:00 - Buy for 4845.366791548566$ of BNB at 13.2013$
2018-01-25 23:00:00 - Sell for 4841.402790931299$ of BNB at 13.1905$
2018-01-27 12:00:00 - Buy for 4841.402790931299$ of BNB at 13.012$
2018-01-29 11:00:00 - Sell for 4830.761527495959$ of BNB at 12.9834$
2018-02-03 07:00:00 - Buy for 4830.761527495959$ of BNB at 9.354$
2018-02-04 13:00:00 - Sell for 4535.617181444651$ of BNB at 8.7825$
2018-02-07 01:00:00 - Buy for 4535.617181444651$ of BNB at 7.9528$
2018-02-11 02:00:00 - Sell for 5046.735293054486$ of BNB at 8.849$
2018-02-12 09:00:00 - Buy for 5046.735293054486$ of BNB at 9.3321$
2018-02-13 15:00:00 - Sell for 4864.433938880326$ of BNB at 8.995$
2018-02-14 13:00:00 - Buy for 4864.433938880326$ of BNB at 9.5458$
2018-02-18 13:00:00 - Sell for 5605.529109249877$ of BNB at 11.0001$
2018-02-20 00:00:00 - Buy for 5605.529109249877$ of BNB at 11.16$
2018-02-20 13:00:00 - Sell for 5406.82415265317$ of BNB at 10.7644$
2018-02-23 21:00:00 - Buy for 5406.82415265317$ of BNB at 9.3321$
2018-02-24 22:00:00 - Sell for 5210.356683362797$ of BNB at 8.993$
2018-02-26 02:00:00 - Buy for 5210.356683362797$ of BNB at 9.3853$
2018-03-01 01:00:00 - Sell for 5825.9752066045685$ of BNB at 10.4942$
2018-03-05 04:00:00 - Buy for 5825.9752066045685$ of BNB at 10.361$
2018-03-06 05:00:00 - Sell for 5655.036449456823$ of BNB at 10.057$
2018-03-10 10:00:00 - Buy for 5655.036449456823$ of BNB at 8.1999$
2018-03-11 06:00:00 - Sell for 5309.592266292038$ of BNB at 7.699$
2018-03-12 00:00:00 - Buy for 5309.592266292038$ of BNB at 8.3$
2018-03-13 06:00:00 - Sell for 5229.244701394896$ of BNB at 8.1744$
2018-03-13 14:00:00 - Buy for 5229.244701394896$ of BNB at 10.8219$
2018-03-15 02:00:00 - Sell for 4038.6648568420096$ of BNB at 8.358$
2018-03-16 15:00:00 - Buy for 4038.6648568420096$ of BNB at 9.2628$
2018-03-17 20:00:00 - Sell for 3834.6562108044855$ of BNB at 8.7949$
2018-03-19 11:00:00 - Buy for 3834.6562108044855$ of BNB at 8.7551$
2018-03-23 05:00:00 - Sell for 4293.057735656054$ of BNB at 9.8017$
2018-03-23 17:00:00 - Buy for 4293.057735656054$ of BNB at 10.6802$
2018-03-26 05:00:00 - Sell for 5072.787833933766$ of BNB at 12.62$
2018-03-28 05:00:00 - Buy for 5072.787833933766$ of BNB at 11.7375$
2018-03-29 06:00:00 - Sell for 4831.8439176468155$ of BNB at 11.18$
2018-03-31 12:00:00 - Buy for 4831.8439176468155$ of BNB at 10.93$
2018-04-04 15:00:00 - Sell for 5358.0418879281515$ of BNB at 12.1203$
2018-04-06 01:00:00 - Buy for 5358.0418879281515$ of BNB at 12.56$
2018-04-06 17:00:00 - Sell for 5217.819884061751$ of BNB at 12.2313$
2018-04-07 12:00:00 - Buy for 5217.819884061751$ of BNB at 12.523$
2018-04-08 16:00:00 - Sell for 5083.197381103964$ of BNB at 12.1999$
2018-04-10 17:00:00 - Buy for 5083.197381103964$ of BNB at 12.095$
2018-04-11 13:00:00 - Sell for 5059.872250500304$ of BNB at 12.0395$
2018-04-12 04:00:00 - Buy for 5059.872250500304$ of BNB at 12.2984$
2018-04-15 03:00:00 - Sell for 5430.81325266734$ of BNB at 13.2$
2018-04-19 08:00:00 - Buy for 5430.81325266734$ of BNB at 12.1295$
2018-04-20 20:00:00 - Sell for 5505.003100226347$ of BNB at 12.2952$
2018-04-21 00:00:00 - Buy for 5505.003100226347$ of BNB at 12.484$
2018-04-23 04:00:00 - Sell for 5716.181086825065$ of BNB at 12.9629$
2018-04-23 11:00:00 - Buy for 5716.181086825065$ of BNB at 13.7265$
2018-04-25 17:00:00 - Sell for 5755.159307764622$ of BNB at 13.8201$
2018-04-26 23:00:00 - Buy for 5755.159307764622$ of BNB at 14.63$
2018-04-29 22:00:00 - Sell for 5911.331436621939$ of BNB at 15.027$
2018-05-02 15:00:00 - Buy for 5911.331436621939$ of BNB at 14.139$
2018-05-04 20:00:00 - Sell for 6017.274670658293$ of BNB at 14.3924$
2018-05-06 01:00:00 - Buy for 6017.274670658293$ of BNB at 14.5828$
2018-05-06 14:00:00 - Sell for 5713.580307600135$ of BNB at 13.8468$
2018-05-08 12:00:00 - Buy for 5713.580307600135$ of BNB at 13.2152$
2018-05-08 15:00:00 - Sell for 5740.731833367228$ of BNB at 13.278$
2018-05-09 16:00:00 - Buy for 5740.731833367228$ of BNB at 14.3018$
2018-05-11 03:00:00 - Sell for 5538.908289070912$ of BNB at 13.799$
2018-05-13 10:00:00 - Buy for 5538.908289070912$ of BNB at 13.1143$
2018-05-14 10:00:00 - Sell for 5262.264859429876$ of BNB at 12.4593$
2018-05-15 06:00:00 - Buy for 5262.264859429876$ of BNB at 13.2184$
2018-05-16 01:00:00 - Sell for 4891.990654854759$ of BNB at 12.2883$
2018-05-17 14:00:00 - Buy for 4891.990654854759$ of BNB at 12.5405$
2018-05-20 04:00:00 - Sell for 5420.998950141911$ of BNB at 13.8966$
2018-05-21 11:00:00 - Buy for 5420.998950141911$ of BNB at 14.0678$
2018-05-23 02:00:00 - Sell for 5102.007854808777$ of BNB at 13.24$
2018-05-25 05:00:00 - Buy for 5102.007854808777$ of BNB at 13.2342$
2018-05-27 03:00:00 - Sell for 4872.740950027621$ of BNB at 12.6395$
2018-05-29 21:00:00 - Buy for 4872.740950027621$ of BNB at 12.6268$
2018-06-04 05:00:00 - Sell for 5503.772248653177$ of BNB at 14.262$
2018-06-05 12:00:00 - Buy for 5503.772248653177$ of BNB at 14.295$
2018-06-08 06:00:00 - Sell for 6264.675018503703$ of BNB at 16.2713$
2018-06-09 14:00:00 - Buy for 6264.675018503703$ of BNB at 16.3784$
2018-06-10 01:00:00 - Sell for 6028.521892653547$ of BNB at 15.761$
2018-06-12 01:00:00 - Buy for 6028.521892653547$ of BNB at 15.1223$
2018-06-13 15:00:00 - Sell for 5709.122612094769$ of BNB at 14.3211$
2018-06-15 06:00:00 - Buy for 5709.122612094769$ of BNB at 14.9131$
2018-06-19 09:00:00 - Sell for 6316.897190080676$ of BNB at 16.5007$
2018-06-21 13:00:00 - Buy for 6316.897190080676$ of BNB at 16.7237$
2018-06-22 18:00:00 - Sell for 6043.502535418108$ of BNB at 15.9999$
2018-06-25 20:00:00 - Buy for 6043.502535418108$ of BNB at 14.93$
2018-06-27 00:00:00 - Sell for 5734.445992498368$ of BNB at 14.1665$
2018-06-28 13:00:00 - Buy for 5734.445992498368$ of BNB at 14.8101$
2018-06-29 12:00:00 - Sell for 5365.678302661334$ of BNB at 13.8577$
2018-06-30 06:00:00 - Buy for 5365.678302661334$ of BNB at 14.4509$
2018-07-01 15:00:00 - Sell for 5323.349636176658$ of BNB at 14.3369$
2018-07-03 01:00:00 - Buy for 5323.349636176658$ of BNB at 14.4822$
2018-07-03 22:00:00 - Sell for 5175.582960274998$ of BNB at 14.0802$
2018-07-07 10:00:00 - Buy for 5175.582960274998$ of BNB at 14.1883$
2018-07-09 07:00:00 - Sell for 5080.156975315001$ of BNB at 13.9267$
2018-07-13 19:00:00 - Buy for 5080.156975315001$ of BNB at 12.171$
2018-07-14 07:00:00 - Sell for 5004.649589164768$ of BNB at 11.9901$
2018-07-15 15:00:00 - Buy for 5004.649589164768$ of BNB at 12.3425$
2018-07-19 02:00:00 - Sell for 5186.832215084293$ of BNB at 12.7918$
2018-07-22 05:00:00 - Buy for 5186.832215084293$ of BNB at 12.319$
2018-07-23 10:00:00 - Sell for 5069.234825874694$ of BNB at 12.0397$
2018-07-25 00:00:00 - Buy for 5069.234825874694$ of BNB at 12.2447$
2018-07-29 16:00:00 - Sell for 5738.125260770261$ of BNB at 13.8604$
2018-07-31 22:00:00 - Buy for 5738.125260770261$ of BNB at 13.954$
2018-08-01 22:00:00 - Sell for 5592.554360504196$ of BNB at 13.6$
2018-08-02 02:00:00 - Buy for 5592.554360504196$ of BNB at 13.6212$
2018-08-02 05:00:00 - Sell for 5539.179322558526$ of BNB at 13.4912$
2018-08-03 01:00:00 - Buy for 5539.179322558526$ of BNB at 13.7209$
2018-08-05 00:00:00 - Sell for 5530.2574688150735$ of BNB at 13.6988$
2018-08-06 14:00:00 - Buy for 5530.2574688150735$ of BNB at 13.6732$
2018-08-07 10:00:00 - Sell for 5493.734763856907$ of BNB at 13.5829$
2018-08-09 23:00:00 - Buy for 5493.734763856907$ of BNB at 12.7654$
2018-08-10 22:00:00 - Sell for 5127.454219767525$ of BNB at 11.9143$
2018-08-13 09:00:00 - Buy for 5127.454219767525$ of BNB at 11.7626$
2018-08-13 17:00:00 - Sell for 4747.513637077526$ of BNB at 10.891$
2018-08-15 14:00:00 - Buy for 4747.513637077526$ of BNB at 10.0637$
2018-08-16 14:00:00 - Sell for 4580.892829957304$ of BNB at 9.7105$
2018-08-17 04:00:00 - Buy for 4580.892829957304$ of BNB at 10.167$
2018-08-18 20:00:00 - Sell for 4402.018584507018$ of BNB at 9.77$
2018-08-20 02:00:00 - Buy for 4402.018584507018$ of BNB at 10.094$
2018-08-20 19:00:00 - Sell for 4256.316740928279$ of BNB at 9.7599$
2018-08-22 09:00:00 - Buy for 4256.316740928279$ of BNB at 9.969$
2018-08-23 02:00:00 - Sell for 4078.3617988459328$ of BNB at 9.5522$
2018-08-24 09:00:00 - Buy for 4078.3617988459328$ of BNB at 9.6396$
2018-08-26 13:00:00 - Sell for 4306.573379647782$ of BNB at 10.179$
2018-08-27 00:00:00 - Buy for 4306.573379647782$ of BNB at 10.1293$
2018-08-29 19:00:00 - Sell for 4675.399696061004$ of BNB at 10.9968$
2018-08-31 21:00:00 - Buy for 4675.399696061004$ of BNB at 10.92$
2018-09-02 20:00:00 - Sell for 4786.633106412345$ of BNB at 11.1798$
2018-09-04 01:00:00 - Buy for 4786.633106412345$ of BNB at 11.3941$
2018-09-05 11:00:00 - Sell for 4425.601301210463$ of BNB at 10.5347$
2018-09-07 12:00:00 - Buy for 4425.601301210463$ of BNB at 10.0162$
2018-09-08 05:00:00 - Sell for 4429.224424817213$ of BNB at 10.0244$
2018-09-08 10:00:00 - Buy for 4429.224424817213$ of BNB at 10.1044$
2018-09-08 12:00:00 - Sell for 4391.1321479361895$ of BNB at 10.0175$
2018-09-10 12:00:00 - Buy for 4391.1321479361895$ of BNB at 9.5063$
2018-09-10 23:00:00 - Sell for 4391.917408726559$ of BNB at 9.508$
2018-09-13 10:00:00 - Buy for 4391.917408726559$ of BNB at 9.5695$
2018-09-16 13:00:00 - Sell for 4550.2549923004835$ of BNB at 9.9145$
2018-09-19 06:00:00 - Buy for 4550.2549923004835$ of BNB at 9.6746$
2018-09-23 01:00:00 - Sell for 4810.441569703232$ of BNB at 10.2278$
2018-09-24 01:00:00 - Buy for 4810.441569703232$ of BNB at 10.2854$
2018-09-24 07:00:00 - Sell for 4745.010883915467$ of BNB at 10.1455$
2018-09-26 20:00:00 - Buy for 4745.010883915467$ of BNB at 9.8024$
2018-09-29 05:00:00 - Sell for 4738.911649326251$ of BNB at 9.7898$
2018-09-30 06:00:00 - Buy for 4738.911649326251$ of BNB at 9.89$
2018-10-01 14:00:00 - Sell for 4762.246836113125$ of BNB at 9.9387$
2018-10-01 17:00:00 - Buy for 4762.246836113125$ of BNB at 9.9774$
2018-10-01 18:00:00 - Sell for 4750.887015448474$ of BNB at 9.9536$
2018-10-02 20:00:00 - Buy for 4750.887015448474$ of BNB at 10.33$
2018-10-06 22:00:00 - Sell for 4794.808574981419$ of BNB at 10.4255$
2018-10-08 05:00:00 - Buy for 4794.808574981419$ of BNB at 10.5261$
2018-10-09 16:00:00 - Sell for 4734.634891209173$ of BNB at 10.394$
2018-10-13 02:00:00 - Buy for 4734.634891209173$ of BNB at 9.6683$
2018-10-17 00:00:00 - Sell for 5002.798484232366$ of BNB at 10.2159$
2018-10-18 10:00:00 - Buy for 5002.798484232366$ of BNB at 10.2075$
2018-10-18 11:00:00 - Sell for 4982.703971584457$ of BNB at 10.1665$
2018-10-20 21:00:00 - Buy for 4982.703971584457$ of BNB at 9.9571$
2018-10-22 08:00:00 - Sell for 4941.269428509948$ of BNB at 9.8743$
2018-10-23 17:00:00 - Buy for 4941.269428509948$ of BNB at 9.8928$
2018-10-24 23:00:00 - Sell for 4936.724147922102$ of BNB at 9.8837$
2018-10-27 00:00:00 - Buy for 4936.724147922102$ of BNB at 9.8196$
2018-10-27 15:00:00 - Sell for 4890.270798369371$ of BNB at 9.7272$
2018-11-01 04:00:00 - Buy for 4890.270798369371$ of BNB at 9.4835$
2018-11-03 13:00:00 - Sell for 4897.8510146119015$ of BNB at 9.4982$
2018-11-04 15:00:00 - Buy for 4897.8510146119015$ of BNB at 9.7009$
2018-11-08 09:00:00 - Sell for 4949.702832402069$ of BNB at 9.8036$
2018-11-13 08:00:00 - Buy for 4949.702832402069$ of BNB at 9.4321$
2018-11-13 19:00:00 - Sell for 4920.105686512238$ of BNB at 9.3757$
2018-11-18 14:00:00 - Buy for 4920.105686512238$ of BNB at 8.0362$
2018-11-19 09:00:00 - Sell for 4376.556517939335$ of BNB at 7.1484$
2018-11-22 02:00:00 - Buy for 4376.556517939335$ of BNB at 6.2945$
2018-11-23 00:00:00 - Sell for 3958.6125791144345$ of BNB at 5.6934$
2018-11-26 10:00:00 - Buy for 3958.6125791144345$ of BNB at 5.1948$
2018-11-27 04:00:00 - Sell for 3740.89955573471$ of BNB at 4.9091$
2018-11-28 08:00:00 - Buy for 3740.89955573471$ of BNB at 5.1997$
2018-11-30 10:00:00 - Sell for 3678.4517065438386$ of BNB at 5.1129$
2018-12-01 21:00:00 - Buy for 3678.4517065438386$ of BNB at 5.3059$
2018-12-03 07:00:00 - Sell for 3551.8595578763357$ of BNB at 5.1233$
2018-12-04 11:00:00 - Buy for 3551.8595578763357$ of BNB at 5.4967$
2018-12-06 11:00:00 - Sell for 3564.2016026587394$ of BNB at 5.5158$
2018-12-09 08:00:00 - Buy for 3564.2016026587394$ of BNB at 4.635$
2018-12-10 22:00:00 - Sell for 3594.4992387201755$ of BNB at 4.6744$
2018-12-12 02:00:00 - Buy for 3594.4992387201755$ of BNB at 4.8459$
2018-12-13 17:00:00 - Sell for 3562.3068148235916$ of BNB at 4.8025$
2018-12-16 10:00:00 - Buy for 3562.3068148235916$ of BNB at 4.6154$
2018-12-21 22:00:00 - Sell for 4162.4050833431875$ of BNB at 5.3929$
2018-12-22 20:00:00 - Buy for 4162.4050833431875$ of BNB at 5.7374$
2018-12-25 04:00:00 - Sell for 3938.447463301349$ of BNB at 5.4287$
2018-12-27 00:00:00 - Buy for 3938.447463301349$ of BNB at 5.6161$
2018-12-27 06:00:00 - Sell for 3803.6618287067868$ of BNB at 5.4239$
2018-12-28 21:00:00 - Buy for 3803.6618287067868$ of BNB at 5.842$
2018-12-30 12:00:00 - Sell for 3778.7251207233107$ of BNB at 5.8037$
2018-12-31 00:00:00 - Buy for 3778.7251207233107$ of BNB at 5.9177$
2019-01-01 15:00:00 - Sell for 3723.1715973100036$ of BNB at 5.8307$
2019-01-02 22:00:00 - Buy for 3723.1715973100036$ of BNB at 6.0597$
2019-01-03 18:00:00 - Sell for 3572.7627640308824$ of BNB at 5.8149$
2019-01-04 21:00:00 - Buy for 3572.7627640308824$ of BNB at 5.9178$
2019-01-10 04:00:00 - Sell for 3935.0620872075583$ of BNB at 6.5179$
2019-01-12 03:00:00 - Buy for 3935.0620872075583$ of BNB at 5.886$
2019-01-12 19:00:00 - Sell for 3906.916298238574$ of BNB at 5.8439$
2019-01-14 21:00:00 - Buy for 3906.916298238574$ of BNB at 5.923$
2019-01-16 07:00:00 - Sell for 3854.938414682741$ of BNB at 5.8442$
2019-01-16 17:00:00 - Buy for 3854.938414682741$ of BNB at 6.0073$
2019-01-21 00:00:00 - Sell for 4114.317188377207$ of BNB at 6.4115$
2019-01-22 03:00:00 - Buy for 4114.317188377207$ of BNB at 6.4664$
2019-01-24 08:00:00 - Sell for 4102.037353888823$ of BNB at 6.4471$
2019-01-25 06:00:00 - Buy for 4102.037353888823$ of BNB at 6.5087$
2019-01-28 09:00:00 - Sell for 4211.068721477246$ of BNB at 6.6817$
2019-01-31 01:00:00 - Buy for 4211.068721477246$ of BNB at 6.1497$
2019-01-31 13:00:00 - Sell for 4197.578948998409$ of BNB at 6.13$
2019-01-31 16:00:00 - Buy for 4197.578948998409$ of BNB at 6.0995$
2019-02-04 06:00:00 - Sell for 4708.899739080517$ of BNB at 6.8425$
2019-02-04 13:00:00 - Buy for 4708.899739080517$ of BNB at 7.0152$
2019-02-08 00:00:00 - Sell for 5188.0996939969245$ of BNB at 7.7291$
2019-02-08 18:00:00 - Buy for 5188.0996939969245$ of BNB at 8.51$
2019-02-12 18:00:00 - Sell for 5603.757316954281$ of BNB at 9.1918$
2019-02-15 10:00:00 - Buy for 5603.757316954281$ of BNB at 9.3373$
2019-02-16 22:00:00 - Sell for 5459.001738269932$ of BNB at 9.0961$
2019-02-18 04:00:00 - Buy for 5459.001738269932$ of BNB at 9.3559$
2019-02-21 11:00:00 - Sell for 6001.523549773196$ of BNB at 10.2857$
2019-02-22 13:00:00 - Buy for 6001.523549773196$ of BNB at 10.71$
2019-02-23 17:00:00 - Sell for 5959.440037299995$ of BNB at 10.6349$
2019-02-24 06:00:00 - Buy for 5959.440037299995$ of BNB at 10.7885$
2019-02-24 17:00:00 - Sell for 5433.290281956041$ of BNB at 9.836$
2019-02-27 15:00:00 - Buy for 5433.290281956041$ of BNB at 9.8412$
2019-03-04 04:00:00 - Sell for 6064.557211638248$ of BNB at 10.9846$
2019-03-05 05:00:00 - Buy for 6064.557211638248$ of BNB at 12.686$
2019-03-08 15:00:00 - Sell for 6758.639713260318$ of BNB at 14.1379$
2019-03-09 18:00:00 - Buy for 6758.639713260318$ of BNB at 14.5359$
2019-03-10 11:00:00 - Sell for 6600.04120844169$ of BNB at 14.1948$
2019-03-11 13:00:00 - Buy for 6600.04120844169$ of BNB at 14.3319$
2019-03-14 04:00:00 - Sell for 6760.346146702393$ of BNB at 14.68$
2019-03-15 08:00:00 - Buy for 6760.346146702393$ of BNB at 14.9997$
2019-03-18 08:00:00 - Sell for 7021.210587305294$ of BNB at 15.5785$
2019-03-22 22:00:00 - Buy for 7021.210587305294$ of BNB at 15.1952$
2019-03-24 05:00:00 - Sell for 6815.082201828506$ of BNB at 14.7491$
2019-03-24 10:00:00 - Buy for 6815.082201828506$ of BNB at 16.8625$
2019-03-26 05:00:00 - Sell for 6640.244273851574$ of BNB at 16.4299$
2019-03-27 12:00:00 - Buy for 6640.244273851574$ of BNB at 16.5662$
2019-03-29 22:00:00 - Sell for 6609.300131082482$ of BNB at 16.489$
2019-03-31 00:00:00 - Buy for 6609.300131082482$ of BNB at 16.8163$
2019-04-04 05:00:00 - Sell for 7480.449774020843$ of BNB at 19.0328$
2019-04-05 15:00:00 - Buy for 7480.449774020843$ of BNB at 19.4207$
2019-04-06 20:00:00 - Sell for 7343.171905588652$ of BNB at 19.0643$
2019-04-10 02:00:00 - Buy for 7343.171905588652$ of BNB at 18.2504$
2019-04-11 05:00:00 - Sell for 7071.943210241849$ of BNB at 17.5763$
2019-04-12 18:00:00 - Buy for 7071.943210241849$ of BNB at 18.3147$
2019-04-16 04:00:00 - Sell for 7326.367436749974$ of BNB at 18.9736$
2019-04-16 23:00:00 - Buy for 7326.367436749974$ of BNB at 19.6408$

In [57]:
import ta

In [60]:
df['RSI'] = ta.momentum.RSIIndicator(df['close'], window = 14).rsi()
df

,open,high,low,close,volume,ma20,ma50,buy_signal,sell_signal,RSI
date,,,,,,,,,,
2017-08-17 04:00:00,4261.48,4313.62,4261.32,4308.83,47.181009,NaN,NaN,False,False,NaN
2017-08-17 05:00:00,4308.83,4328.69,4291.37,4315.32,23.234916,NaN,NaN,False,False,NaN
2017-08-17 06:00:00,4330.29,4345.45,4309.37,4324.35,7.229691,NaN,NaN,False,False,NaN
2017-08-17 07:00:00,4316.62,4349.99,4287.41,4349.99,4.443249,NaN,NaN,False,False,NaN
2017-08-17 08:00:00,4333.32,4377.85,4333.32,4360.69,0.972807,NaN,NaN,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...
2023-07-03 06:00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,30599.5055,30558.3664,True,False,54.549107
2023-07-03 07:00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,30605.6280,30563.1230,True,False,55.885094
2023-07-03 08:00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,30611.3345,30566.9202,True,False,53.034081
2023-07-03 09:00:00,30640.11,30670.00,30602.29,30610.61,833.620010,30615.9670,30569.9348,True,False,50.037249
2023-07-03 10:00:00,30610.60,30623.08,30605.66,30615.85,91.875210,30617.2480,30573.4178,True,False,50.571362