In [127]:
import pandas as pd     # we import as pd so everytime when we call we just us pd instead of pandas
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [128]:
pd.__version__

'3.0.2'

In [129]:
data = {
    "date": ["2022-01-01", "2022-01-02", "2022-01-03", "2022-01-04"],
    "close": [150.0, 152.0, 153.0, 154.0],
    "volume": [1000, 1200, 1300, 1250],
}

df = pd.DataFrame(data)
#print(df)
df # Because we are in jupyter notebook calling this give better output

         date  close  volume
0  2022-01-01 150.00    1000
1  2022-01-02 152.00    1200
2  2022-01-03 153.00    1300
3  2022-01-04 154.00    1250

In [130]:
print(df.index) # can access index
print(list(df.index)) # can print them as lists

#print(df['volume'])
print(df.loc[2]) # We access 2nd row
print(df.loc[2]['volume']) # We access specific value
print(df.loc[2][['volume', 'close']]) # We can also access in such way using a list
print(df[['volume','close']]) # this prints columns

RangeIndex(start=0, stop=4, step=1)
[0, 1, 2, 3]
date      2022-01-03
close         153.00
volume          1300
Name: 2, dtype: object
1300
volume     1300
close    153.00
Name: 2, dtype: object
   volume  close
0    1000 150.00
1    1200 152.00
2    1300 153.00
3    1250 154.00

In [131]:
df['volume'] > 1300 # Gives output false as nothing in volume column is larger than 1300

0    False
1    False
2    False
3    False
Name: volume, dtype: bool

In [132]:
df.loc[df['volume'] >= 1250]
df.loc[(df['volume'] >= 1250) & (df['close'] > 153)]
df.loc[(df['volume'] >= 1250) | (df['close'] > 153)] # | symbol means "or"
df['volume'].loc[(df['volume'] >= 1300) | (df['close'] >153)] # We have isolated only volume part

2    1300
3    1250
Name: volume, dtype: int64

In [133]:
df = pd.read_csv('APPL_1D.csv') # 
df                              # with this df we call to print it

            time   open   high    low  close       volume    Volume MA
0     1320240600  12.14  12.16  11.99  12.06 328255052.00 565663058.20
1     1320327000  12.11  12.25  12.00  12.24 441524796.00 547110249.40
2     1320413400  12.20  12.25  12.12  12.15 302228240.00 535440799.60
3     1320676200  12.14  12.14  12.02  12.13 270274636.00 526828854.80
4     1320762600  12.21  12.38  12.19  12.33 400439768.00 516566707.40
...          ...    ...    ...    ...    ...          ...          ...
2915  1686058200 179.97 180.12 177.43 179.21  64848374.00  58818603.75
2916  1686144600 178.44 181.21 177.32 177.82  61944615.00  59649490.80
2917  1686231000 177.90 180.84 177.46 180.57  50214881.00  59474009.80
2918  1686317400 181.50 182.23 180.63 180.96  48899973.00  59443274.65
2919  1686576600 181.27    NaN    NaN    NaN          NaN          NaN

[2920 rows x 7 columns]

In [134]:
df.describe() # firsthand statistic breakdown of data
# count tells how many rows we have in each column

               time    open    high     low   close        volume    Volume MA
count       2920.00 2920.00 2919.00 2919.00 2919.00       2919.00      2919.00
mean  1503502927.40   59.74   60.38   59.07   59.75  200558014.51 202115717.49
std    105701072.41   51.30   51.90   50.66   51.31  171035615.19 148989947.08
min   1320240600.00    0.00   11.27   11.03   11.04   35195860.00  50684940.65
25%   1412062200.00   21.83   22.09   21.62   21.85   91766241.00 101733696.10
50%   1503451800.00   36.49   36.72   36.18   36.58  137148384.00 138776456.20
75%   1595057400.00   93.83   94.55   92.27   93.84  247976166.00 250714603.00
max   1686576600.00  182.63  184.95  180.63  180.96 1506113440.00 807241634.00

In [135]:
df = df.drop('Volume MA', axis=1) #method/ function drop helps us to remove Volume MA from data set. axis=1 means column
df

            time   open   high    low  close       volume
0     1320240600  12.14  12.16  11.99  12.06 328255052.00
1     1320327000  12.11  12.25  12.00  12.24 441524796.00
2     1320413400  12.20  12.25  12.12  12.15 302228240.00
3     1320676200  12.14  12.14  12.02  12.13 270274636.00
4     1320762600  12.21  12.38  12.19  12.33 400439768.00
...          ...    ...    ...    ...    ...          ...
2915  1686058200 179.97 180.12 177.43 179.21  64848374.00
2916  1686144600 178.44 181.21 177.32 177.82  61944615.00
2917  1686231000 177.90 180.84 177.46 180.57  50214881.00
2918  1686317400 181.50 182.23 180.63 180.96  48899973.00
2919  1686576600 181.27    NaN    NaN    NaN          NaN

[2920 rows x 6 columns]

In [136]:
df.isnull() # everywhere where data is not null it will return false

       time   open   high    low  close  volume
0     False  False  False  False  False   False
1     False  False  False  False  False   False
2     False  False  False  False  False   False
3     False  False  False  False  False   False
4     False  False  False  False  False   False
...     ...    ...    ...    ...    ...     ...
2915  False  False  False  False  False   False
2916  False  False  False  False  False   False
2917  False  False  False  False  False   False
2918  False  False  False  False  False   False
2919  False  False   True   True   True    True

[2920 rows x 6 columns]

In [137]:
df['high'].isnull() # This would return only for column high

0       False
1       False
2       False
3       False
4       False
        ...
2915    False
2916    False
2917    False
2918    False
2919     True
Name: high, Length: 2920, dtype: bool

In [138]:
df.loc[df['high'].isnull()]

            time   open  high  low  close  volume
2919  1686576600 181.27   NaN  NaN    NaN     NaN

In [139]:
df = df.drop(2919)
df

            time   open   high    low  close       volume
0     1320240600  12.14  12.16  11.99  12.06 328255052.00
1     1320327000  12.11  12.25  12.00  12.24 441524796.00
2     1320413400  12.20  12.25  12.12  12.15 302228240.00
3     1320676200  12.14  12.14  12.02  12.13 270274636.00
4     1320762600  12.21  12.38  12.19  12.33 400439768.00
...          ...    ...    ...    ...    ...          ...
2914  1685971800 182.63 184.95 178.03 179.58 121946497.00
2915  1686058200 179.97 180.12 177.43 179.21  64848374.00
2916  1686144600 178.44 181.21 177.32 177.82  61944615.00
2917  1686231000 177.90 180.84 177.46 180.57  50214881.00
2918  1686317400 181.50 182.23 180.63 180.96  48899973.00

[2919 rows x 6 columns]

In [140]:
df.describe()

               time    open    high     low   close        volume
count       2919.00 2919.00 2919.00 2919.00 2919.00       2919.00
mean  1503440209.46   59.70   60.38   59.07   59.75  200558014.51
std    105664827.31   51.26   51.90   50.66   51.31  171035615.19
min   1320240600.00    0.00   11.27   11.03   11.04   35195860.00
25%   1412040600.00   21.83   22.09   21.62   21.85   91766241.00
50%   1503408600.00   36.47   36.72   36.18   36.58  137148384.00
75%   1594949400.00   93.36   94.55   92.27   93.84  247976166.00
max   1686317400.00  182.63  184.95  180.63  180.96 1506113440.00

In [141]:
df["time"] = pd.to_datetime(df["time"], unit='s') # Take the column time from dataframe and change it to date time. Then inside method we state that df['time] column is in seconds
print(df["time"])

0      2011-11-02 13:30:00
1      2011-11-03 13:30:00
2      2011-11-04 13:30:00
3      2011-11-07 14:30:00
4      2011-11-08 14:30:00
               ...
2914   2023-06-05 13:30:00
2915   2023-06-06 13:30:00
2916   2023-06-07 13:30:00
2917   2023-06-08 13:30:00
2918   2023-06-09 13:30:00
Name: time, Length: 2919, dtype: datetime64[s]

In [142]:
df['open'] ==0 #not helpful because the 0 is somewhere in the middle of the data set.
df.loc[df['open'] == 0] # locating specific row

                   time  open  high   low  close       volume
985 2015-10-05 13:30:00  0.00 25.31 24.78  25.17 208258972.00

In [143]:
df.set_index('time', inplace=True)
df

                      open   high    low  close       volume
time
2011-11-02 13:30:00  12.14  12.16  11.99  12.06 328255052.00
2011-11-03 13:30:00  12.11  12.25  12.00  12.24 441524796.00
2011-11-04 13:30:00  12.20  12.25  12.12  12.15 302228240.00
2011-11-07 14:30:00  12.14  12.14  12.02  12.13 270274636.00
2011-11-08 14:30:00  12.21  12.38  12.19  12.33 400439768.00
...                    ...    ...    ...    ...          ...
2023-06-05 13:30:00 182.63 184.95 178.03 179.58 121946497.00
2023-06-06 13:30:00 179.97 180.12 177.43 179.21  64848374.00
2023-06-07 13:30:00 178.44 181.21 177.32 177.82  61944615.00
2023-06-08 13:30:00 177.90 180.84 177.46 180.57  50214881.00
2023-06-09 13:30:00 181.50 182.23 180.63 180.96  48899973.00

[2919 rows x 5 columns]

In [144]:
df.loc['2023-03-13'] # Specific day
df.loc['2023-03'] # a month of march
df.loc['2023'] # year of 2023 data 
df.loc['2021':] # from 2021 till today
df.loc['2021': '2022'] # in between those years

                      open   high    low  close       volume
time
2021-01-04 14:30:00 131.55 131.64 124.89 127.50 143301887.00
2021-01-05 14:30:00 126.99 129.80 126.54 129.08  97664898.00
2021-01-06 14:30:00 125.84 129.12 124.52 124.74 155087970.00
2021-01-07 14:30:00 126.47 129.69 125.98 128.99 109578157.00
2021-01-08 14:30:00 130.48 130.68 128.31 130.10 105158245.00
...                    ...    ...    ...    ...          ...
2022-12-23 14:30:00 130.54 132.03 129.26 131.48  63814893.00
2022-12-27 14:30:00 131.00 131.03 128.35 129.65  69007830.00
2022-12-28 14:30:00 129.29 130.65 125.50 125.67  85438391.00
2022-12-29 14:30:00 127.62 130.10 127.36 129.23  75703710.00
2022-12-30 14:30:00 128.04 129.57 127.06 129.55  77034209.00

[503 rows x 5 columns]

In [ ]:
df.iloc[3:10]
# del df['close']

# Time in video 43:25