In [ ]:
# Backtest an Automated Trading Strategy in Python

In [13]:
import pandas as pd

In [14]:
df= pd.read_csv('BTC-USDT.csv')
df

                date      open      high       low     close       volume
0      1502942400000   4261.48   4313.62   4261.32   4308.83    47.181009
1      1502946000000   4308.83   4328.69   4291.37   4315.32    23.234916
2      1502949600000   4330.29   4345.45   4309.37   4324.35     7.229691
3      1502953200000   4316.62   4349.99   4287.41   4349.99     4.443249
4      1502956800000   4333.32   4377.85   4333.32   4360.69     0.972807
...              ...       ...       ...       ...       ...          ...
51404  1688364000000  30673.61  30678.41  30606.00  30651.25  1036.522350
51405  1688367600000  30651.25  30759.80  30636.65  30667.19  1758.796390
51406  1688371200000  30667.19  30700.92  30599.07  30640.12  1390.909010
51407  1688374800000  30640.11  30670.00  30602.29  30610.61   833.620010
51408  1688378400000  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 6 columns]

In [15]:
df['date'] = pd.to_datetime(df['date'], unit ="ms")
df

                     date      open      high       low     close       volume
0     2017-08-17 04:00:00   4261.48   4313.62   4261.32   4308.83    47.181009
1     2017-08-17 05:00:00   4308.83   4328.69   4291.37   4315.32    23.234916
2     2017-08-17 06:00:00   4330.29   4345.45   4309.37   4324.35     7.229691
3     2017-08-17 07:00:00   4316.62   4349.99   4287.41   4349.99     4.443249
4     2017-08-17 08:00:00   4333.32   4377.85   4333.32   4360.69     0.972807
...                   ...       ...       ...       ...       ...          ...
51404 2023-07-03 06:00:00  30673.61  30678.41  30606.00  30651.25  1036.522350
51405 2023-07-03 07:00:00  30651.25  30759.80  30636.65  30667.19  1758.796390
51406 2023-07-03 08:00:00  30667.19  30700.92  30599.07  30640.12  1390.909010
51407 2023-07-03 09:00:00  30640.11  30670.00  30602.29  30610.61   833.620010
51408 2023-07-03 10:00:00  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 6 columns]

In [16]:
df.set_index(df['date'],inplace=True)
del df['date']
df

                         open      high       low     close       volume
date
2017-08-17 04:00:00   4261.48   4313.62   4261.32   4308.83    47.181009
2017-08-17 05:00:00   4308.83   4328.69   4291.37   4315.32    23.234916
2017-08-17 06:00:00   4330.29   4345.45   4309.37   4324.35     7.229691
2017-08-17 07:00:00   4316.62   4349.99   4287.41   4349.99     4.443249
2017-08-17 08:00:00   4333.32   4377.85   4333.32   4360.69     0.972807
...                       ...       ...       ...       ...          ...
2023-07-03 06:00:00  30673.61  30678.41  30606.00  30651.25  1036.522350
2023-07-03 07:00:00  30651.25  30759.80  30636.65  30667.19  1758.796390
2023-07-03 08:00:00  30667.19  30700.92  30599.07  30640.12  1390.909010
2023-07-03 09:00:00  30640.11  30670.00  30602.29  30610.61   833.620010
2023-07-03 10:00:00  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 5 columns]

In [18]:
# Creating new columns for Moving Averages
# 50 moving average based on close price. We want to do computation of rolling period 50. Computing mean the average price

df['ma50'] = df['close'].rolling(50).mean()
df['ma200'] = df['close'].rolling(200).mean()
df

,open,high,low,close,volume,ma50,ma200
date,,,,,,,
2017-08-17 04:00:00,4261.48,4313.62,4261.32,4308.83,47.181009,NaN,NaN
2017-08-17 05:00:00,4308.83,4328.69,4291.37,4315.32,23.234916,NaN,NaN
2017-08-17 06:00:00,4330.29,4345.45,4309.37,4324.35,7.229691,NaN,NaN
2017-08-17 07:00:00,4316.62,4349.99,4287.41,4349.99,4.443249,NaN,NaN
2017-08-17 08:00:00,4333.32,4377.85,4333.32,4360.69,0.972807,NaN,NaN
...,...,...,...,...,...,...,...
2023-07-03 06:00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,30558.3664,30477.55635
2023-07-03 07:00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,30563.1230,30478.25515
2023-07-03 08:00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,30566.9202,30478.88960
2023-07-03 09:00:00,30640.11,30670.00,30602.29,30610.61,833.620010,30569.9348,30478.95005
2023-07-03 10:00:00,30610.60,30623.08,30605.66,30615.85,91.875210,30573.4178,30478.92280

In [22]:
df['buy_signal'] = False
df['sell_signal'] = False
df.loc[df['ma50']> df['ma200'], 'buy_signal'] =True # Moving Average cross over
df.loc[df['ma50']< df['ma200'], 'sell_signal'] = True # Moving Average cross over
df

,open,high,low,close,volume,ma50,ma200,buy_signal,sell_signal
date,,,,,,,,,
2017-08-17 04:00:00,4261.48,4313.62,4261.32,4308.83,47.181009,NaN,NaN,False,False
2017-08-17 05:00:00,4308.83,4328.69,4291.37,4315.32,23.234916,NaN,NaN,False,False
2017-08-17 06:00:00,4330.29,4345.45,4309.37,4324.35,7.229691,NaN,NaN,False,False
2017-08-17 07:00:00,4316.62,4349.99,4287.41,4349.99,4.443249,NaN,NaN,False,False
2017-08-17 08:00:00,4333.32,4377.85,4333.32,4360.69,0.972807,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...
2023-07-03 06:00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,30558.3664,30477.55635,True,False
2023-07-03 07:00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,30563.1230,30478.25515,True,False
2023-07-03 08:00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,30566.9202,30478.88960,True,False
2023-07-03 09:00:00,30640.11,30670.00,30602.29,30610.61,833.620010,30569.9348,30478.95005,True,False
2023-07-03 10:00:00,30610.60,30623.08,30605.66,30615.85,91.875210,30573.4178,30478.92280,True,False

In [23]:
df['sell_signal'].value_counts()

sell_signal
False    26943
True     24466
Name: count, dtype: int64

In [25]:
# Backtesting

balance = 1000
position = None

for index, row in df.iterrows():    # Loop going to return 2 values 
    # buy condition
    if position is None and row['buy_signal'] is True:
        buy_price = row['close']
        usd_size = balance          # How much we are going to buy
        position = {
            'buy_price': buy_price,
            'usd_size': usd_size
        }
        print(f'{index} - Bought Bitcoin for {usd_size}$ at price of {buy_price}$')

2017-08-25 11:00:00 - Bought Bitcoin for 1000$ at price of 4361.27$