In [5]:
import pandas as pd     # we import as pd so everytime when we call we just us pd instead of pandas
pd.set_option('display.float_format', lambda x: '%.4f' % x)

In [6]:
pd.__version__

'3.0.2'

In [7]:
data = {
    "date": ["2022-01-01", "2022-01-02", "2022-01-03", "2022-01-04"],
    "close": [150.0, 152.0, 153.0, 154.0],
    "volume": [1000, 1200, 1300, 1250],
}

df = pd.DataFrame(data)
#print(df)
df # Because we are in jupyter notebook calling this give better output

         date    close  volume
0  2022-01-01 150.0000    1000
1  2022-01-02 152.0000    1200
2  2022-01-03 153.0000    1300
3  2022-01-04 154.0000    1250

In [8]:
print(df.index) # can access index
print(list(df.index)) # can print them as lists

#print(df['volume'])
print(df.loc[2]) # We access 2nd row
print(df.loc[2]['volume']) # We access specific value
print(df.loc[2][['volume', 'close']]) # We can also access in such way using a list
print(df[['volume','close']]) # this prints columns

RangeIndex(start=0, stop=4, step=1)
[0, 1, 2, 3]
date      2022-01-03
close       153.0000
volume          1300
Name: 2, dtype: object
1300
volume       1300
close    153.0000
Name: 2, dtype: object
   volume    close
0    1000 150.0000
1    1200 152.0000
2    1300 153.0000
3    1250 154.0000

In [9]:
df['volume'] > 1300 # Gives output false as nothing in volume column is larger than 1300

0    False
1    False
2    False
3    False
Name: volume, dtype: bool

In [10]:
df.loc[df['volume'] >= 1250]
df.loc[(df['volume'] >= 1250) & (df['close'] > 153)]
df.loc[(df['volume'] >= 1250) | (df['close'] > 153)] # | symbol means "or"
df['volume'].loc[(df['volume'] >= 1300) | (df['close'] >153)] # We have isolated only volume part

2    1300
3    1250
Name: volume, dtype: int64

In [11]:
df = pd.read_csv('APPL_1D.csv') # 
df                              # with this df we call to print it

,time,open,high,low,close,volume,Volume MA
0,1320240600,12.1448,12.1554,11.9936,12.0634,328255052.0000,565663058.2000
1,1320327000,12.1138,12.2452,12.0012,12.2352,441524796.0000,547110249.4000
2,1320413400,12.2036,12.2464,12.1165,12.1493,302228240.0000,535440799.6000
3,1320676200,12.1393,12.1420,12.0246,12.1338,270274636.0000,526828854.8000
4,1320762600,12.2091,12.3849,12.1894,12.3311,400439768.0000,516566707.4000
...,...,...,...,...,...,...,...
2915,1686058200,179.9650,180.1200,177.4300,179.2100,64848374.0000,58818603.7500
2916,1686144600,178.4400,181.2100,177.3200,177.8200,61944615.0000,59649490.8000
2917,1686231000,177.8950,180.8400,177.4600,180.5700,50214881.0000,59474009.8000
2918,1686317400,181.5000,182.2300,180.6300,180.9600,48899973.0000,59443274.6500
2919,1686576600,181.2700,NaN,NaN,NaN,NaN,NaN

In [12]:
df.describe() # firsthand statistic breakdown of data
# count tells how many rows we have in each column

,time,open,high,low,close,volume,Volume MA
count,2920.0000,2920.0000,2919.0000,2919.0000,2919.0000,2919.0000,2919.0000
mean,1503502927.3973,59.7426,60.3816,59.0700,59.7542,200558014.5115,202115717.4892
std,105701072.4096,51.3041,51.9049,50.6559,51.3130,171035615.1915,148989947.0812
min,1320240600.0000,0.0000,11.2663,11.0286,11.0362,35195860.0000,50684940.6500
25%,1412062200.0000,21.8347,22.0909,21.6194,21.8520,91766241.0000,101733696.1000
50%,1503451800.0000,36.4903,36.7245,36.1785,36.5761,137148384.0000,138776456.2000
75%,1595057400.0000,93.8277,94.5549,92.2734,93.8406,247976166.0000,250714603.0000
max,1686576600.0000,182.6300,184.9510,180.6300,180.9600,1506113440.0000,807241634.0000

In [13]:
df = df.drop('Volume MA', axis=1) #method/ function drop helps us to remove Volume MA from data set. axis=1 means column
df

            time     open     high      low    close         volume
0     1320240600  12.1448  12.1554  11.9936  12.0634 328255052.0000
1     1320327000  12.1138  12.2452  12.0012  12.2352 441524796.0000
2     1320413400  12.2036  12.2464  12.1165  12.1493 302228240.0000
3     1320676200  12.1393  12.1420  12.0246  12.1338 270274636.0000
4     1320762600  12.2091  12.3849  12.1894  12.3311 400439768.0000
...          ...      ...      ...      ...      ...            ...
2915  1686058200 179.9650 180.1200 177.4300 179.2100  64848374.0000
2916  1686144600 178.4400 181.2100 177.3200 177.8200  61944615.0000
2917  1686231000 177.8950 180.8400 177.4600 180.5700  50214881.0000
2918  1686317400 181.5000 182.2300 180.6300 180.9600  48899973.0000
2919  1686576600 181.2700      NaN      NaN      NaN            NaN

[2920 rows x 6 columns]

In [14]:
df.isnull() # everywhere where data is not null it will return false

       time   open   high    low  close  volume
0     False  False  False  False  False   False
1     False  False  False  False  False   False
2     False  False  False  False  False   False
3     False  False  False  False  False   False
4     False  False  False  False  False   False
...     ...    ...    ...    ...    ...     ...
2915  False  False  False  False  False   False
2916  False  False  False  False  False   False
2917  False  False  False  False  False   False
2918  False  False  False  False  False   False
2919  False  False   True   True   True    True

[2920 rows x 6 columns]

In [15]:
df['high'].isnull() # This would return only for column high

0       False
1       False
2       False
3       False
4       False
        ...
2915    False
2916    False
2917    False
2918    False
2919     True
Name: high, Length: 2920, dtype: bool

In [16]:
df.loc[df['high'].isnull()]

            time     open  high  low  close  volume
2919  1686576600 181.2700   NaN  NaN    NaN     NaN

In [17]:
df = df.drop(2919)
df

            time     open     high      low    close         volume
0     1320240600  12.1448  12.1554  11.9936  12.0634 328255052.0000
1     1320327000  12.1138  12.2452  12.0012  12.2352 441524796.0000
2     1320413400  12.2036  12.2464  12.1165  12.1493 302228240.0000
3     1320676200  12.1393  12.1420  12.0246  12.1338 270274636.0000
4     1320762600  12.2091  12.3849  12.1894  12.3311 400439768.0000
...          ...      ...      ...      ...      ...            ...
2914  1685971800 182.6300 184.9510 178.0350 179.5800 121946497.0000
2915  1686058200 179.9650 180.1200 177.4300 179.2100  64848374.0000
2916  1686144600 178.4400 181.2100 177.3200 177.8200  61944615.0000
2917  1686231000 177.8950 180.8400 177.4600 180.5700  50214881.0000
2918  1686317400 181.5000 182.2300 180.6300 180.9600  48899973.0000

[2919 rows x 6 columns]

In [18]:
df.describe()

                 time      open      high       low     close          volume
count       2919.0000 2919.0000 2919.0000 2919.0000 2919.0000       2919.0000
mean  1503440209.4553   59.7010   60.3816   59.0700   59.7542  200558014.5115
std    105664827.3087   51.2636   51.9049   50.6559   51.3130  171035615.1915
min   1320240600.0000    0.0000   11.2663   11.0286   11.0362   35195860.0000
25%   1412040600.0000   21.8318   22.0909   21.6194   21.8520   91766241.0000
50%   1503408600.0000   36.4703   36.7245   36.1785   36.5761  137148384.0000
75%   1594949400.0000   93.3571   94.5549   92.2734   93.8406  247976166.0000
max   1686317400.0000  182.6300  184.9510  180.6300  180.9600 1506113440.0000

In [19]:
df["time"] = pd.to_datetime(df["time"], unit='s') # Take the column time from dataframe and change it to date time. Then inside method we state that df['time] column is in seconds
print(df["time"])

0      2011-11-02 13:30:00
1      2011-11-03 13:30:00
2      2011-11-04 13:30:00
3      2011-11-07 14:30:00
4      2011-11-08 14:30:00
               ...
2914   2023-06-05 13:30:00
2915   2023-06-06 13:30:00
2916   2023-06-07 13:30:00
2917   2023-06-08 13:30:00
2918   2023-06-09 13:30:00
Name: time, Length: 2919, dtype: datetime64[s]

In [20]:
df['open'] ==0 #not helpful because the 0 is somewhere in the middle of the data set.
df.loc[df['open'] == 0] # locating specific row

                   time   open    high     low   close         volume
985 2015-10-05 13:30:00 0.0000 25.3069 24.7843 25.1729 208258972.0000

In [21]:
df.set_index('time', inplace=True)
df

                        open     high      low    close         volume
time
2011-11-02 13:30:00  12.1448  12.1554  11.9936  12.0634 328255052.0000
2011-11-03 13:30:00  12.1138  12.2452  12.0012  12.2352 441524796.0000
2011-11-04 13:30:00  12.2036  12.2464  12.1165  12.1493 302228240.0000
2011-11-07 14:30:00  12.1393  12.1420  12.0246  12.1338 270274636.0000
2011-11-08 14:30:00  12.2091  12.3849  12.1894  12.3311 400439768.0000
...                      ...      ...      ...      ...            ...
2023-06-05 13:30:00 182.6300 184.9510 178.0350 179.5800 121946497.0000
2023-06-06 13:30:00 179.9650 180.1200 177.4300 179.2100  64848374.0000
2023-06-07 13:30:00 178.4400 181.2100 177.3200 177.8200  61944615.0000
2023-06-08 13:30:00 177.8950 180.8400 177.4600 180.5700  50214881.0000
2023-06-09 13:30:00 181.5000 182.2300 180.6300 180.9600  48899973.0000

[2919 rows x 5 columns]

In [22]:
df.loc['2023-03-13'] # Specific day
df.loc['2023-03'] # a month of march
df.loc['2023'] # year of 2023 data 
df.loc['2021':] # from 2021 till today
df.loc['2021': '2022'] # in between those years

                        open     high      low    close         volume
time
2021-01-04 14:30:00 131.5531 131.6433 124.8927 127.5036 143301887.0000
2021-01-05 14:30:00 126.9913 129.7993 126.5381 129.0801  97664898.0000
2021-01-06 14:30:00 125.8385 129.1194 124.5202 124.7350 155087970.0000
2021-01-07 14:30:00 126.4691 129.6909 125.9765 128.9914 109578157.0000
2021-01-08 14:30:00 130.4792 130.6762 128.3116 130.1047 105158245.0000
...                      ...      ...      ...      ...            ...
2022-12-23 14:30:00 130.5399 132.0305 129.2636 131.4771  63814893.0000
2022-12-27 14:30:00 130.9985 131.0284 128.3462 129.6524  69007830.0000
2022-12-28 14:30:00 129.2935 130.6470 125.5045 125.6740  85438391.0000
2022-12-29 14:30:00 127.6184 130.1025 127.3591 129.2337  75703710.0000
2022-12-30 14:30:00 128.0371 129.5727 127.0600 129.5527  77034209.0000

[503 rows x 5 columns]

In [23]:
df.iloc[3:10]
#del df['close']

                       open    high     low   close         volume
time
2011-11-07 14:30:00 12.1393 12.1420 12.0246 12.1338 270274636.0000
2011-11-08 14:30:00 12.2091 12.3849 12.1894 12.3311 400439768.0000
2011-11-09 14:30:00 12.0501 12.1690 11.9669 11.9988 558684332.0000
2011-11-10 14:30:00 12.0519 12.0573 11.6002 11.6934 744981736.0000
2011-11-11 14:30:00 11.7356 11.7990 11.5428 11.6752 653784524.0000
2011-11-14 14:30:00 11.6418 11.6943 11.4803 11.5125 433062432.0000
2011-11-15 14:30:00 11.5592 11.8233 11.5182 11.8030 430979704.0000

In [24]:
df['low_high_avg'] = (df['low'] + df['high']) / 2 # This one line has calculated whole column with values. This is also better than to make a loop and calculate line by line
df

,open,high,low,close,volume,low_high_avg
time,,,,,,
2011-11-02 13:30:00,12.1448,12.1554,11.9936,12.0634,328255052.0000,12.0745
2011-11-03 13:30:00,12.1138,12.2452,12.0012,12.2352,441524796.0000,12.1232
2011-11-04 13:30:00,12.2036,12.2464,12.1165,12.1493,302228240.0000,12.1815
2011-11-07 14:30:00,12.1393,12.1420,12.0246,12.1338,270274636.0000,12.0833
2011-11-08 14:30:00,12.2091,12.3849,12.1894,12.3311,400439768.0000,12.2871
...,...,...,...,...,...,...
2023-06-05 13:30:00,182.6300,184.9510,178.0350,179.5800,121946497.0000,181.4930
2023-06-06 13:30:00,179.9650,180.1200,177.4300,179.2100,64848374.0000,178.7750
2023-06-07 13:30:00,178.4400,181.2100,177.3200,177.8200,61944615.0000,179.2650
2023-06-08 13:30:00,177.8950,180.8400,177.4600,180.5700,50214881.0000,179.1500
2023-06-09 13:30:00,181.5000,182.2300,180.6300,180.9600,48899973.0000,181.4300

In [25]:
df.loc[df['open']==0] # We again locate the row, column where we have 0 as value

,open,high,low,close,volume,low_high_avg
time,,,,,,
2015-10-05 13:30:00,0.0000,25.3069,24.7843,25.1729,208258972.0000,25.0456

In [26]:
df.loc[df['open'] == 0, 'open'] = df['low_high_avg'] # we have replaced that 0 value with avg value
df.loc[df['open'] ==0] # We can no longer locate value that is 0

Empty DataFrame
Columns: [open, high, low, close, volume, low_high_avg]
Index: []

In [27]:
df.loc['2015-10-05'] # We see that for the same row open value has been replaced and is no longer 0

,open,high,low,close,volume,low_high_avg
time,,,,,,
2015-10-05 13:30:00,25.0456,25.3069,24.7843,25.1729,208258972.0000,25.0456

In [28]:
df.describe()

           open      high       low     close          volume  low_high_avg
count 2919.0000 2919.0000 2919.0000 2919.0000       2919.0000     2919.0000
mean    59.7096   60.3816   59.0700   59.7542  200558014.5115       59.7258
std     51.2557   51.9049   50.6559   51.3130  171035615.1915       51.2783
min     11.1834   11.2663   11.0286   11.0362   35195860.0000       11.1474
25%     21.8403   22.0909   21.6194   21.8520   91766241.0000       21.8652
50%     36.4703   36.7245   36.1785   36.5761  137148384.0000       36.5485
75%     93.3571   94.5549   92.2734   93.8406  247976166.0000       93.4553
max    182.6300  184.9510  180.6300  180.9600 1506113440.0000      181.4930

In [29]:
mean_prices = df['close'].mean()
median_prices = df['close'].median()
std_prices = df['close'].std()

print("Average closing prices:", round(mean_prices,2))
print("Median closing prices:",round(median_prices,2))
print("Standard deviation of closing prices:", round(std_prices,2))

Average closing prices: 59.75
Median closing prices: 36.58
Standard deviation of closing prices: 51.31

In [ ]:
df['moving_average'] = df['close'].rolling(20).mean() #Rolling(2) means that moving average takes last two value of close. That is why first is NaN
df

In [ ]:
df['dayly_returns'] = df['close'].pct_change()
df['volatility'] = df['dayly_returns'].rolling(30).std()
df

In [ ]:
df.sort_values(by='dayly_returns', ascending=True, inplace=True)
df['change'] = (df['close'] - df['open']) / df['close']
df.sort_values(by='change', ascending=True, inplace=True)
df