In [115]:
# Native python package. No need to install it
import datetime

In [116]:
print(datetime.date(2026,5,18)) # Access date

2026-05-18

In [117]:
print(datetime.datetime(2026,5,18,19,45,26)) # Access date and time

2026-05-18 19:45:26

In [118]:
print(datetime.date.today())
print(datetime.datetime.now())

2026-05-18
2026-05-18 20:09:44.439239

In [119]:
d1 = '2026-05-18'
print(datetime.datetime.strptime(d1,'%Y-%m-%d'))

2026-05-18 00:00:00

In [120]:
d2 = '2026-05-18 09:35:02'
print(datetime.datetime.strptime(d2,'%Y-%m-%d %H:%M:%S'))

2026-05-18 09:35:02

In [121]:
# Another python native library time. Also does not need to be installed
import time
t1 = time.time()
print(t1) # Provides time in seconds since 1970s

print(datetime.datetime.fromtimestamp(t1)) # This line translates time to human friendly output

t2 = time.time() * 1000 # We would provide time in miliseconds
print(t2)
print(datetime.datetime.fromtimestamp(t2 / 1000)) # For this to work we need to convert time stamp back to seconds

1779124184.4919763
2026-05-18 20:09:44.491976
1779124184492.6113
2026-05-18 20:09:44.492611

In [122]:
d2 = '2026-05-18 09:35:02'
d2_datetime = datetime.datetime.strptime(d2,'%Y-%m-%d %H:%M:%S')
print(d2_datetime)
print(d2_datetime.timestamp()) # With this line we get back to second format. In case we need to transform it the other way aroun

2026-05-18 09:35:02
1779086102.0

In [123]:
import pandas as pd
df = pd.read_csv('BTC-USDT.csv')
df

                date      open      high       low     close       volume
0      1502942400000   4261.48   4313.62   4261.32   4308.83    47.181009
1      1502946000000   4308.83   4328.69   4291.37   4315.32    23.234916
2      1502949600000   4330.29   4345.45   4309.37   4324.35     7.229691
3      1502953200000   4316.62   4349.99   4287.41   4349.99     4.443249
4      1502956800000   4333.32   4377.85   4333.32   4360.69     0.972807
...              ...       ...       ...       ...       ...          ...
51404  1688364000000  30673.61  30678.41  30606.00  30651.25  1036.522350
51405  1688367600000  30651.25  30759.80  30636.65  30667.19  1758.796390
51406  1688371200000  30667.19  30700.92  30599.07  30640.12  1390.909010
51407  1688374800000  30640.11  30670.00  30602.29  30610.61   833.620010
51408  1688378400000  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 6 columns]

In [124]:
print(df['date'].dtype)
df['date'] = pd.to_datetime(df['date'], unit ="ms")
df

int64

                     date      open      high       low     close       volume
0     2017-08-17 04:00:00   4261.48   4313.62   4261.32   4308.83    47.181009
1     2017-08-17 05:00:00   4308.83   4328.69   4291.37   4315.32    23.234916
2     2017-08-17 06:00:00   4330.29   4345.45   4309.37   4324.35     7.229691
3     2017-08-17 07:00:00   4316.62   4349.99   4287.41   4349.99     4.443249
4     2017-08-17 08:00:00   4333.32   4377.85   4333.32   4360.69     0.972807
...                   ...       ...       ...       ...       ...          ...
51404 2023-07-03 06:00:00  30673.61  30678.41  30606.00  30651.25  1036.522350
51405 2023-07-03 07:00:00  30651.25  30759.80  30636.65  30667.19  1758.796390
51406 2023-07-03 08:00:00  30667.19  30700.92  30599.07  30640.12  1390.909010
51407 2023-07-03 09:00:00  30640.11  30670.00  30602.29  30610.61   833.620010
51408 2023-07-03 10:00:00  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 6 columns]

In [125]:
df['weekday'] = df['date'].dt.weekday # We created a new column weekday. Which shows an integer of a weekday
df

,date,open,high,low,close,volume,weekday
0,2017-08-17 04:00:00,4261.48,4313.62,4261.32,4308.83,47.181009,3
1,2017-08-17 05:00:00,4308.83,4328.69,4291.37,4315.32,23.234916,3
2,2017-08-17 06:00:00,4330.29,4345.45,4309.37,4324.35,7.229691,3
3,2017-08-17 07:00:00,4316.62,4349.99,4287.41,4349.99,4.443249,3
4,2017-08-17 08:00:00,4333.32,4377.85,4333.32,4360.69,0.972807,3
...,...,...,...,...,...,...,...
51404,2023-07-03 06:00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,0
51405,2023-07-03 07:00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,0
51406,2023-07-03 08:00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,0
51407,2023-07-03 09:00:00,30640.11,30670.00,30602.29,30610.61,833.620010,0
51408,2023-07-03 10:00:00,30610.60,30623.08,30605.66,30615.85,91.875210,0

In [126]:
# Mapping

day_name_map = {
    0: 'Monday',
    1: 'Tuesday',
    2: 'Wednesday',
    3: 'Thursday',
    4: 'Friday',
    5: 'Saturday',
    6: 'Sunday'
}

df['weekday'] = df['weekday'].map(day_name_map)
df

,date,open,high,low,close,volume,weekday
0,2017-08-17 04:00:00,4261.48,4313.62,4261.32,4308.83,47.181009,Thursday
1,2017-08-17 05:00:00,4308.83,4328.69,4291.37,4315.32,23.234916,Thursday
2,2017-08-17 06:00:00,4330.29,4345.45,4309.37,4324.35,7.229691,Thursday
3,2017-08-17 07:00:00,4316.62,4349.99,4287.41,4349.99,4.443249,Thursday
4,2017-08-17 08:00:00,4333.32,4377.85,4333.32,4360.69,0.972807,Thursday
...,...,...,...,...,...,...,...
51404,2023-07-03 06:00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,Monday
51405,2023-07-03 07:00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,Monday
51406,2023-07-03 08:00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,Monday
51407,2023-07-03 09:00:00,30640.11,30670.00,30602.29,30610.61,833.620010,Monday
51408,2023-07-03 10:00:00,30610.60,30623.08,30605.66,30615.85,91.875210,Monday

In [ ]:
df['date_diff'] = df['date'] - df['date'].shift(1) # shift(1) shift the value by 1
df

,date,open,high,low,close,volume,weekday,date_diff
0,2017-08-17 04:00:00,4261.48,4313.62,4261.32,4308.83,47.181009,Thursday,NaT
1,2017-08-17 05:00:00,4308.83,4328.69,4291.37,4315.32,23.234916,Thursday,0 days 01:00:00
2,2017-08-17 06:00:00,4330.29,4345.45,4309.37,4324.35,7.229691,Thursday,0 days 01:00:00
3,2017-08-17 07:00:00,4316.62,4349.99,4287.41,4349.99,4.443249,Thursday,0 days 01:00:00
4,2017-08-17 08:00:00,4333.32,4377.85,4333.32,4360.69,0.972807,Thursday,0 days 01:00:00
...,...,...,...,...,...,...,...,...
51404,2023-07-03 06:00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,Monday,0 days 01:00:00
51405,2023-07-03 07:00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,Monday,0 days 01:00:00
51406,2023-07-03 08:00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,Monday,0 days 01:00:00
51407,2023-07-03 09:00:00,30640.11,30670.00,30602.29,30610.61,833.620010,Monday,0 days 01:00:00
51408,2023-07-03 10:00:00,30610.60,30623.08,30605.66,30615.85,91.875210,Monday,0 days 01:00:00

In [128]:
df['date_diff'].value_counts()

date_diff
0 days 01:00:00    51354
0 days 00:00:00       26
0 days 02:00:00        9
0 days 03:00:00        5
0 days 04:00:00        3
0 days 07:00:00        2
0 days 11:00:00        2
0 days 08:00:00        2
0 days 05:00:00        2
1 days 10:00:00        1
0 days 09:00:00        1
0 days 06:00:00        1
Name: count, dtype: int64

In [ ]:
df.groupby('weekday').agg({'volume':'mean'}) # We see that on weekend volumes are down in trading cryptos.

                volume
weekday
Friday     3525.469924
Monday     3444.452027
Saturday   2371.131363
Sunday     2445.885570
Thursday   3518.008325
Tuesday    3498.625967
Wednesday  3617.011268

In [ ]:
# Homework